package event

import (
	"context"
	"encoding/json"
	"sort"
	"strings"
	"time"

	"github.com/FelixSeptem/baymax/core/types"
	runtimeconfig "github.com/FelixSeptem/baymax/runtime/config"
	runtimediag "github.com/FelixSeptem/baymax/runtime/diagnostics"
)

type RuntimeRecorder struct {
	manager         *runtimeconfig.Manager
	exporterRuntime *runtimeExporterRuntime
}

type RuntimeRecorderOption func(*runtimeRecorderOptionSet)

type runtimeRecorderOptionSet struct {
	exporterResolver RuntimeExporterResolver
	exporterFactory  map[string]RuntimeExporterFactory
}

func WithRuntimeExporterResolver(resolver RuntimeExporterResolver) RuntimeRecorderOption {
	return func(opts *runtimeRecorderOptionSet) {
		if opts == nil || resolver == nil {
			return
		}
		opts.exporterResolver = resolver
	}
}

func WithRuntimeExporterFactory(profile string, factory RuntimeExporterFactory) RuntimeRecorderOption {
	return func(opts *runtimeRecorderOptionSet) {
		if opts == nil || factory == nil {
			return
		}
		normalized := strings.ToLower(strings.TrimSpace(profile))
		if normalized == "" {
			return
		}
		if opts.exporterFactory == nil {
			opts.exporterFactory = map[string]RuntimeExporterFactory{}
		}
		opts.exporterFactory[normalized] = factory
	}
}

func NewRuntimeRecorder(manager *runtimeconfig.Manager, options ...RuntimeRecorderOption) *RuntimeRecorder {
	opts := runtimeRecorderOptionSet{
		exporterFactory: map[string]RuntimeExporterFactory{},
	}
	for i := range options {
		if options[i] == nil {
			continue
		}
		options[i](&opts)
	}
	resolver := opts.exporterResolver
	if resolver == nil {
		resolver = newDefaultRuntimeExporterResolver(opts.exporterFactory)
	}
	return &RuntimeRecorder{
		manager:         manager,
		exporterRuntime: newRuntimeExporterRuntime(resolver),
	}
}

func (r *RuntimeRecorder) ExportSnapshot() RuntimeExportSnapshot {
	if r == nil || r.exporterRuntime == nil {
		return RuntimeExportSnapshot{}
	}
	return r.exporterRuntime.Snapshot()
}

func (r *RuntimeRecorder) Close() {
	if r == nil || r.exporterRuntime == nil {
		return
	}
	r.exporterRuntime.Close()
}

func (r *RuntimeRecorder) OnEvent(ctx context.Context, ev types.Event) {
	if r == nil || r.manager == nil {
		return
	}
	if ctx == nil {
		ctx = context.Background()
	}
	payload := ev.Payload
	if len(payload) > 0 {
		payload = r.manager.RedactPayload(payload)
	}
	switch ev.Type {
	case types.EventTypeActionTimeline:
		if timeline, ok := ParseActionTimeline(types.Event{
			Version:   ev.Version,
			Type:      ev.Type,
			RunID:     ev.RunID,
			Iteration: ev.Iteration,
			Time:      ev.Time,
			Payload:   payload,
		}); ok {
			r.manager.RecordRunTimelineEvent(
				timeline.RunID,
				string(timeline.Phase),
				string(timeline.Status),
				timeline.Sequence,
				timeline.Time,
			)
		}
	case "run.finished":
		errorClass := payloadString(payload, "error_class")
		status := payloadString(payload, "status")
		if status == "" {
			if errorClass != "" {
				status = "failed"
			} else {
				status = "success"
			}
		}
		exportSnapshot := r.ExportSnapshot()
		exportProfile := normalizeRuntimeObservabilityExportProfile(payloadStringOrFallback(payload, "observability_export_profile", exportSnapshot.Profile))
		exportStatus := normalizeRuntimeObservabilityExportStatus(payloadStringOrFallback(payload, "observability_export_status", exportSnapshot.Status), exportProfile)
		bundleTotal := payloadInt(payload, "diagnostics_bundle_total")
		bundleStatus := normalizeRuntimeDiagnosticsBundleStatus(payloadString(payload, "diagnostics_bundle_last_status"))
		bundleReasonCode := normalizeRuntimeDiagnosticsBundleReasonCode(payloadString(payload, "diagnostics_bundle_last_reason_code"), bundleStatus)
		bundleSchemaVersion := normalizeRuntimeDiagnosticsBundleSchemaVersion(payloadString(payload, "diagnostics_bundle_last_schema_version"))
		if shouldAutoGenerateDiagnosticsBundle(r.manager, bundleTotal, bundleStatus, bundleSchemaVersion, bundleReasonCode) {
			result, err := r.manager.GenerateDiagnosticsBundle(ctx, runtimeconfig.DiagnosticsBundleGenerateRequest{
				RunID:              ev.RunID,
				RunFinishedPayload: payload,
			})
			if err != nil {
				code := runtimeconfig.DiagnosticsBundleErrorCode(err)
				if bundleStatus == "" {
					bundleStatus = runtimeconfig.RuntimeDiagnosticsBundleStatusFailed
				}
				if bundleReasonCode == "" {
					bundleReasonCode = normalizeRuntimeDiagnosticsBundleReasonCode(code, bundleStatus)
				}
				if bundleSchemaVersion == "" {
					bundleSchemaVersion = runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1
				}
				if bundleTotal <= 0 {
					bundleTotal = 1
				}
			} else {
				if bundleTotal <= 0 {
					bundleTotal = result.Total
				}
				if bundleStatus == "" {
					bundleStatus = normalizeRuntimeDiagnosticsBundleStatus(result.Status)
				}
				if bundleReasonCode == "" {
					bundleReasonCode = normalizeRuntimeDiagnosticsBundleReasonCode(result.ReasonCode, bundleStatus)
				}
				if bundleSchemaVersion == "" {
					bundleSchemaVersion = normalizeRuntimeDiagnosticsBundleSchemaVersion(result.Manifest.SchemaVersion)
				}
			}
		}
		decision := payloadString(payload, "decision")
		runtimeReadinessStatus := payloadString(payload, "runtime_readiness_status")
		budgetDecision := payloadString(payload, "budget_decision")
		evalSummary := payloadAnyMap(payload, "eval_summary")
		budgetSnapshot := payloadAnyMap(payload, "budget_snapshot")
		inferentialAdvisory := buildInferentialAdvisory(
			r.manager.EffectiveConfig().Runtime.Eval.Agent,
			evalSummary,
			runtimeReadinessStatus,
			budgetDecision,
			decision,
		)
		r.manager.RecordRunOwned(runtimediag.RunRecord{
			Time:                                        ev.Time,
			RunID:                                       ev.RunID,
			Status:                                      status,
			Iterations:                                  ev.Iteration,
			ToolCalls:                                   payloadInt(payload, "tool_calls"),
			LatencyMs:                                   payloadInt64(payload, "latency_ms"),
			ErrorClass:                                  errorClass,
			PolicyKind:                                  payloadString(payload, "policy_kind"),
			NamespaceTool:                               payloadString(payload, "namespace_tool"),
			FilterStage:                                 payloadString(payload, "filter_stage"),
			Decision:                                    decision,
			ReasonCode:                                  payloadString(payload, "reason_code"),
			Severity:                                    payloadString(payload, "severity"),
			AlertDispatchStatus:                         payloadString(payload, "alert_dispatch_status"),
			AlertDispatchFailureReason:                  payloadString(payload, "alert_dispatch_failure_reason"),
			AlertDeliveryMode:                           payloadString(payload, "alert_delivery_mode"),
			AlertRetryCount:                             payloadInt(payload, "alert_retry_count"),
			AlertQueueDropped:                           payloadBool(payload, "alert_queue_dropped"),
			AlertQueueDropCount:                         payloadInt(payload, "alert_queue_drop_count"),
			AlertCircuitState:                           payloadString(payload, "alert_circuit_state"),
			AlertCircuitOpenReason:                      payloadString(payload, "alert_circuit_open_reason"),
			ModelProvider:                               payloadString(payload, "model_provider"),
			FallbackUsed:                                payloadBool(payload, "fallback_used"),
			FallbackInitial:                             payloadString(payload, "fallback_initial"),
			FallbackPath:                                payloadString(payload, "fallback_path"),
			RequiredCapabilities:                        payloadString(payload, "required_capabilities"),
			FallbackReason:                              payloadString(payload, "fallback_reason"),
			MemoryMode:                                  payloadString(payload, "memory_mode"),
			MemoryProvider:                              payloadString(payload, "memory_provider"),
			MemoryProfile:                               payloadString(payload, "memory_profile"),
			MemoryContractVersion:                       payloadString(payload, "memory_contract_version"),
			MemoryQueryTotal:                            payloadInt(payload, "memory_query_total"),
			MemoryUpsertTotal:                           payloadInt(payload, "memory_upsert_total"),
			MemoryDeleteTotal:                           payloadInt(payload, "memory_delete_total"),
			MemoryErrorTotal:                            payloadInt(payload, "memory_error_total"),
			MemoryFallbackTotal:                         payloadInt(payload, "memory_fallback_total"),
			MemoryFallbackReasonCode:                    payloadString(payload, "memory_fallback_reason_code"),
			MemoryLatencyMsP95:                          payloadInt64(payload, "memory_latency_ms_p95"),
			MemoryScopeSelected:                         payloadString(payload, "memory_scope_selected"),
			MemoryBudgetUsed:                            payloadInt(payload, "memory_budget_used"),
			MemoryHits:                                  payloadInt(payload, "memory_hits"),
			MemoryRerankStats:                           payloadIntMap(payload, "memory_rerank_stats"),
			MemoryLifecycleAction:                       payloadString(payload, "memory_lifecycle_action"),
			ObservabilityExportProfile:                  exportProfile,
			ObservabilityExportStatus:                   exportStatus,
			ObservabilityExportErrorTotal:               payloadIntOrFallback(payload, "observability_export_error_total", exportSnapshot.ErrorTotal),
			ObservabilityExportDropTotal:                payloadIntOrFallback(payload, "observability_export_drop_total", exportSnapshot.DropTotal),
			ObservabilityExportQueueDepthPeak:           payloadIntOrFallback(payload, "observability_export_queue_depth_peak", exportSnapshot.QueueDepthPeak),
			DiagnosticsBundleTotal:                      bundleTotal,
			DiagnosticsBundleLastStatus:                 bundleStatus,
			DiagnosticsBundleLastReasonCode:             bundleReasonCode,
			DiagnosticsBundleLastSchemaVersion:          bundleSchemaVersion,
			SandboxMode:                                 payloadString(payload, "sandbox_mode"),
			SandboxBackend:                              payloadString(payload, "sandbox_backend"),
			SandboxProfile:                              payloadString(payload, "sandbox_profile"),
			SandboxSessionMode:                          payloadString(payload, "sandbox_session_mode"),
			SandboxRequiredCapabilities:                 payloadStringSliceCSV(payload, "sandbox_required_capabilities"),
			SandboxDecision:                             payloadString(payload, "sandbox_decision"),
			SandboxReasonCode:                           payloadString(payload, "sandbox_reason_code"),
			SandboxEgressAction:                         payloadString(payload, "sandbox_egress_action"),
			SandboxEgressViolationTotal:                 payloadInt(payload, "sandbox_egress_violation_total"),
			SandboxEgressPolicySource:                   payloadString(payload, "sandbox_egress_policy_source"),
			SandboxFallbackUsed:                         payloadBool(payload, "sandbox_fallback_used"),
			SandboxFallbackReason:                       payloadString(payload, "sandbox_fallback_reason"),
			SandboxTimeoutTotal:                         payloadInt(payload, "sandbox_timeout_total"),
			SandboxLaunchFailedTotal:                    payloadInt(payload, "sandbox_launch_failed_total"),
			SandboxCapabilityMismatchTotal:              payloadInt(payload, "sandbox_capability_mismatch_total"),
			SandboxQueueWaitMsP95:                       payloadInt64(payload, "sandbox_queue_wait_ms_p95"),
			SandboxExecLatencyMsP95:                     payloadInt64(payload, "sandbox_exec_latency_ms_p95"),
			SandboxExitCodeLast:                         payloadInt(payload, "sandbox_exit_code_last"),
			SandboxOOMTotal:                             payloadInt(payload, "sandbox_oom_total"),
			SandboxResourceCPUMsTotal:                   payloadInt64(payload, "sandbox_resource_cpu_ms_total"),
			SandboxResourceMemoryPeakBytesP95:           payloadInt64(payload, "sandbox_resource_memory_peak_bytes_p95"),
			SandboxRolloutPhase:                         payloadString(payload, "sandbox_rollout_phase"),
			SandboxRolloutEffectiveRatio:                payloadFloat64(payload, "sandbox_rollout_effective_ratio"),
			SandboxHealthBudgetStatus:                   payloadString(payload, "sandbox_health_budget_status"),
			SandboxHealthBudgetBreachTotal:              payloadInt(payload, "sandbox_health_budget_breach_total"),
			SandboxFreezeState:                          payloadBool(payload, "sandbox_freeze_state"),
			SandboxFreezeReasonCode:                     payloadString(payload, "sandbox_freeze_reason_code"),
			SandboxCapacityAction:                       payloadString(payload, "sandbox_capacity_action"),
			SandboxCapacityQueueDepth:                   payloadInt(payload, "sandbox_capacity_queue_depth"),
			SandboxCapacityInflight:                     payloadInt(payload, "sandbox_capacity_inflight"),
			PrefixHash:                                  payloadString(payload, "prefix_hash"),
			AssembleLatencyMs:                           payloadInt64(payload, "assemble_latency_ms"),
			AssembleStatus:                              payloadString(payload, "assemble_status"),
			GuardViolation:                              payloadString(payload, "guard_violation"),
			AssembleStageStatus:                         payloadString(payload, "assemble_stage_status"),
			Stage2SkipReason:                            payloadString(payload, "stage2_skip_reason"),
			Stage2RouterMode:                            payloadString(payload, "stage2_router_mode"),
			Stage2RouterDecision:                        payloadString(payload, "stage2_router_decision"),
			Stage2RouterReason:                          payloadString(payload, "stage2_router_reason"),
			Stage2RouterLatencyMs:                       payloadInt64(payload, "stage2_router_latency_ms"),
			Stage2RouterError:                           payloadString(payload, "stage2_router_error"),
			Stage1LatencyMs:                             payloadInt64(payload, "stage1_latency_ms"),
			Stage2LatencyMs:                             payloadInt64(payload, "stage2_latency_ms"),
			Stage2Provider:                              payloadString(payload, "stage2_provider"),
			Stage2Profile:                               payloadString(payload, "stage2_profile"),
			Stage2TemplateProfile:                       payloadString(payload, "stage2_template_profile"),
			Stage2TemplateResolutionSource:              payloadString(payload, "stage2_template_resolution_source"),
			Stage2HintApplied:                           payloadBool(payload, "stage2_hint_applied"),
			Stage2HintMismatchReason:                    payloadString(payload, "stage2_hint_mismatch_reason"),
			Stage2HitCount:                              payloadInt(payload, "stage2_hit_count"),
			Stage2Source:                                payloadString(payload, "stage2_source"),
			Stage2Reason:                                payloadString(payload, "stage2_reason"),
			Stage2ReasonCode:                            payloadString(payload, "stage2_reason_code"),
			Stage2ErrorLayer:                            payloadString(payload, "stage2_error_layer"),
			CA3PressureZone:                             payloadStringCompat(payload, "context_pressure_zone", "ca3_pressure_zone"),
			CA3PressureReason:                           payloadStringCompat(payload, "context_pressure_reason", "ca3_pressure_reason"),
			CA3PressureTrigger:                          payloadStringCompat(payload, "context_pressure_trigger", "ca3_pressure_trigger"),
			CA3ZoneResidencyMs:                          payloadInt64MapCompat(payload, "context_pressure_zone_residency_ms", "ca3_zone_residency_ms"),
			CA3TriggerCounts:                            payloadIntMapCompat(payload, "context_pressure_trigger_counts", "ca3_trigger_counts"),
			CA3CompressionRatio:                         payloadFloat64Compat(payload, "context_compaction_compression_ratio", "ca3_compression_ratio"),
			CA3SpillCount:                               payloadIntCompat(payload, "context_spill_count", "ca3_spill_count"),
			CA3SwapBackCount:                            payloadIntCompat(payload, "context_swap_back_count", "ca3_swap_back_count"),
			CA3CompactionMode:                           payloadStringCompat(payload, "context_compaction_mode", "ca3_compaction_mode"),
			CA3CompactionFallback:                       payloadBoolCompat(payload, "context_compaction_fallback", "ca3_compaction_fallback"),
			CA3CompactionFallbackReason:                 payloadStringCompat(payload, "context_compaction_fallback_reason", "ca3_compaction_fallback_reason"),
			CA3CompactionQualityScore:                   payloadFloat64Compat(payload, "context_compaction_quality_score", "ca3_compaction_quality_score"),
			CA3CompactionQualityReason:                  payloadStringCompat(payload, "context_compaction_quality_reason", "ca3_compaction_quality_reason"),
			CA3CompactionEmbeddingProvider:              payloadStringCompat(payload, "context_compaction_embedding_provider", "ca3_compaction_embedding_provider"),
			CA3CompactionEmbeddingSimilarity:            payloadFloat64Compat(payload, "context_compaction_embedding_similarity", "ca3_compaction_embedding_similarity"),
			CA3CompactionEmbeddingContribution:          payloadFloat64Compat(payload, "context_compaction_embedding_contribution", "ca3_compaction_embedding_contribution"),
			CA3CompactionEmbeddingStatus:                payloadStringCompat(payload, "context_compaction_embedding_status", "ca3_compaction_embedding_status"),
			CA3CompactionEmbeddingFallbackReason:        payloadStringCompat(payload, "context_compaction_embedding_fallback_reason", "ca3_compaction_embedding_fallback_reason"),
			CA3CompactionRerankerUsed:                   payloadBoolCompat(payload, "context_compaction_reranker_used", "ca3_compaction_reranker_used"),
			CA3CompactionRerankerProvider:               payloadStringCompat(payload, "context_compaction_reranker_provider", "ca3_compaction_reranker_provider"),
			CA3CompactionRerankerModel:                  payloadStringCompat(payload, "context_compaction_reranker_model", "ca3_compaction_reranker_model"),
			CA3CompactionRerankerThresholdSource:        payloadStringCompat(payload, "context_compaction_reranker_threshold_source", "ca3_compaction_reranker_threshold_source"),
			CA3CompactionRerankerThresholdHit:           payloadBoolCompat(payload, "context_compaction_reranker_threshold_hit", "ca3_compaction_reranker_threshold_hit"),
			CA3CompactionRerankerFallbackReason:         payloadStringCompat(payload, "context_compaction_reranker_fallback_reason", "ca3_compaction_reranker_fallback_reason"),
			CA3CompactionRerankerProfileVersion:         payloadStringCompat(payload, "context_compaction_reranker_profile_version", "ca3_compaction_reranker_profile_version"),
			CA3CompactionRerankerRolloutHit:             payloadBoolCompat(payload, "context_compaction_reranker_rollout_hit", "ca3_compaction_reranker_rollout_hit"),
			CA3CompactionRerankerThresholdDrift:         payloadFloat64Compat(payload, "context_compaction_reranker_threshold_drift", "ca3_compaction_reranker_threshold_drift"),
			CA3RetainedEvidence:                         payloadIntCompat(payload, "context_compaction_retained_evidence_count", "ca3_compaction_retained_evidence_count"),
			ContextCompactionOutcomeClass:               payloadString(payload, "context_compaction_outcome_class"),
			ContextRefDiscoverCount:                     payloadInt(payload, "context_ref_discover_count"),
			ContextRefResolveCount:                      payloadInt(payload, "context_ref_resolve_count"),
			ContextEditEstimatedSavedTokens:             payloadInt(payload, "context_edit_estimated_saved_tokens"),
			ContextEditGateDecision:                     payloadString(payload, "context_edit_gate_decision"),
			ContextSwapbackRelevanceScore:               payloadFloat64(payload, "context_swapback_relevance_score"),
			ContextSwapbackRankingStrategy:              payloadString(payload, "context_swapback_ranking_strategy"),
			ContextSwapbackCandidateWindow:              payloadInt(payload, "context_swapback_candidate_window"),
			ContextLifecycleTierStats:                   payloadIntMap(payload, "context_lifecycle_tier_stats"),
			ContextTierTransitionReason:                 payloadString(payload, "context_tier_transition_reason"),
			ContextColdStoreGovernanceAction:            payloadString(payload, "context_cold_store_governance_action"),
			ContextRecoveryConsistencyMarker:            payloadString(payload, "context_recovery_consistency_marker"),
			ContextRecapSource:                          payloadString(payload, "context_recap_source"),
			RecapStatus:                                 payloadString(payload, "recap_status"),
			TeamID:                                      payloadString(payload, "team_id"),
			TeamStrategy:                                payloadString(payload, "team_strategy"),
			TeamTaskTotal:                               payloadInt(payload, "team_task_total"),
			TeamTaskFailed:                              payloadInt(payload, "team_task_failed"),
			TeamTaskCanceled:                            payloadInt(payload, "team_task_canceled"),
			TeamRemoteTaskTotal:                         payloadInt(payload, "team_remote_task_total"),
			TeamRemoteTaskFailed:                        payloadInt(payload, "team_remote_task_failed"),
			WorkflowID:                                  payloadString(payload, "workflow_id"),
			WorkflowStatus:                              payloadString(payload, "workflow_status"),
			WorkflowStepTotal:                           payloadInt(payload, "workflow_step_total"),
			WorkflowStepFailed:                          payloadInt(payload, "workflow_step_failed"),
			WorkflowRemoteStepTotal:                     payloadInt(payload, "workflow_remote_step_total"),
			WorkflowRemoteStepFailed:                    payloadInt(payload, "workflow_remote_step_failed"),
			WorkflowSubgraphExpansionTotal:              payloadInt(payload, "workflow_subgraph_expansion_total"),
			WorkflowConditionTemplateTotal:              payloadInt(payload, "workflow_condition_template_total"),
			WorkflowGraphCompileFailed:                  payloadBool(payload, "workflow_graph_compile_failed"),
			WorkflowResumeCount:                         payloadInt(payload, "workflow_resume_count"),
			TaskID:                                      payloadString(payload, "task_id"),
			A2ATaskTotal:                                payloadInt(payload, "a2a_task_total"),
			A2ATaskFailed:                               payloadInt(payload, "a2a_task_failed"),
			PeerID:                                      payloadString(payload, "peer_id"),
			A2AErrorLayer:                               payloadString(payload, "a2a_error_layer"),
			A2ADeliveryMode:                             payloadString(payload, "a2a_delivery_mode"),
			A2ADeliveryFallbackUsed:                     payloadBool(payload, "a2a_delivery_fallback_used"),
			A2ADeliveryFallbackReason:                   payloadString(payload, "a2a_delivery_fallback_reason"),
			A2AVersionLocal:                             payloadString(payload, "a2a_version_local"),
			A2AVersionPeer:                              payloadString(payload, "a2a_version_peer"),
			A2AVersionNegotiationResult:                 payloadString(payload, "a2a_version_negotiation_result"),
			A2AAsyncReportTotal:                         payloadInt(payload, "a2a_async_report_total"),
			A2AAsyncReportFailed:                        payloadInt(payload, "a2a_async_report_failed"),
			A2AAsyncReportRetryTotal:                    payloadInt(payload, "a2a_async_report_retry_total"),
			A2AAsyncReportDedupTotal:                    payloadInt(payload, "a2a_async_report_dedup_total"),
			AsyncAwaitTotal:                             payloadInt(payload, "async_await_total"),
			AsyncTimeoutTotal:                           payloadInt(payload, "async_timeout_total"),
			AsyncLateReportTotal:                        payloadInt(payload, "async_late_report_total"),
			AsyncReportDedupTotal:                       payloadInt(payload, "async_report_dedup_total"),
			AsyncReconcilePollTotal:                     payloadInt(payload, "async_reconcile_poll_total"),
			AsyncReconcileTerminalByPollTotal:           payloadInt(payload, "async_reconcile_terminal_by_poll_total"),
			AsyncReconcileErrorTotal:                    payloadInt(payload, "async_reconcile_error_total"),
			AsyncTerminalConflictTotal:                  payloadInt(payload, "async_terminal_conflict_total"),
			ComposerManaged:                             payloadBool(payload, "composer_managed"),
			SchedulerBackend:                            payloadString(payload, "scheduler_backend"),
			SchedulerQoSMode:                            payloadString(payload, "scheduler_qos_mode"),
			SchedulerBackendFallback:                    payloadBool(payload, "scheduler_backend_fallback"),
			SchedulerBackendFallbackReason:              payloadString(payload, "scheduler_backend_fallback_reason"),
			SchedulerQueueTotal:                         payloadInt(payload, "scheduler_queue_total"),
			SchedulerClaimTotal:                         payloadInt(payload, "scheduler_claim_total"),
			SchedulerReclaimTotal:                       payloadInt(payload, "scheduler_reclaim_total"),
			SchedulerPriorityClaimTotal:                 payloadInt(payload, "scheduler_priority_claim_total"),
			SchedulerFairnessYieldTotal:                 payloadInt(payload, "scheduler_fairness_yield_total"),
			SchedulerRetryBackoffTotal:                  payloadInt(payload, "scheduler_retry_backoff_total"),
			SchedulerDeadLetterTotal:                    payloadInt(payload, "scheduler_dead_letter_total"),
			SchedulerDelayedTaskTotal:                   payloadInt(payload, "scheduler_delayed_task_total"),
			SchedulerDelayedClaimTotal:                  payloadInt(payload, "scheduler_delayed_claim_total"),
			SchedulerDelayedWaitMsP95:                   payloadInt64(payload, "scheduler_delayed_wait_ms_p95"),
			TaskBoardManualControlTotal:                 payloadInt(payload, "task_board_manual_control_total"),
			TaskBoardManualControlSuccessTotal:          payloadInt(payload, "task_board_manual_control_success_total"),
			TaskBoardManualControlRejectedTotal:         payloadInt(payload, "task_board_manual_control_rejected_total"),
			TaskBoardManualControlDedupTotal:            payloadInt(payload, "task_board_manual_control_idempotent_dedup_total"),
			TaskBoardManualControlByAction:              payloadIntMap(payload, "task_board_manual_control_by_action"),
			TaskBoardManualControlByReason:              payloadIntMap(payload, "task_board_manual_control_by_reason"),
			SubagentChildTotal:                          payloadInt(payload, "subagent_child_total"),
			SubagentChildFailed:                         payloadInt(payload, "subagent_child_failed"),
			SubagentBudgetRejectTotal:                   payloadInt(payload, "subagent_budget_reject_total"),
			CollabHandoffTotal:                          payloadInt(payload, "collab_handoff_total"),
			CollabDelegationTotal:                       payloadInt(payload, "collab_delegation_total"),
			CollabAggregationTotal:                      payloadInt(payload, "collab_aggregation_total"),
			CollabAggregationStrategy:                   payloadString(payload, "collab_aggregation_strategy"),
			CollabFailFastTotal:                         payloadInt(payload, "collab_fail_fast_total"),
			CollabRetryTotal:                            payloadInt(payload, "collab_retry_total"),
			CollabRetrySuccessTotal:                     payloadInt(payload, "collab_retry_success_total"),
			CollabRetryExhaustedTotal:                   payloadInt(payload, "collab_retry_exhausted_total"),
			RecoveryEnabled:                             payloadBool(payload, "recovery_enabled"),
			RecoveryResumeBoundary:                      payloadString(payload, "recovery_resume_boundary"),
			RecoveryInflightPolicy:                      payloadString(payload, "recovery_inflight_policy"),
			RecoveryRecovered:                           payloadBool(payload, "recovery_recovered"),
			RecoveryReplayTotal:                         payloadInt(payload, "recovery_replay_total"),
			RecoveryTimeoutReentryTotal:                 payloadInt(payload, "recovery_timeout_reentry_total"),
			RecoveryTimeoutReentryExhaustedTotal:        payloadInt(payload, "recovery_timeout_reentry_exhausted_total"),
			RecoveryConflict:                            payloadBool(payload, "recovery_conflict"),
			RecoveryConflictCode:                        payloadString(payload, "recovery_conflict_code"),
			StateSnapshotVersion:                        normalizeStateSnapshotVersion(payloadString(payload, "state_snapshot_version")),
			StateRestoreAction:                          normalizeStateRestoreAction(payloadString(payload, "state_restore_action")),
			StateRestoreConflictCode:                    normalizeStateRestoreConflictCode(payloadString(payload, "state_restore_conflict_code")),
			StateRestoreSource:                          normalizeStateRestoreSource(payloadString(payload, "state_restore_source")),
			SnapshotEntropyRetention:                    payloadIntMap(payload, "snapshot_entropy_retention"),
			SnapshotEntropyQuota:                        payloadIntMap(payload, "snapshot_entropy_quota"),
			SnapshotEntropyCleanup:                      payloadIntMap(payload, "snapshot_entropy_cleanup"),
			RecoveryFallbackUsed:                        payloadBool(payload, "recovery_fallback_used"),
			RecoveryFallbackReason:                      payloadString(payload, "recovery_fallback_reason"),
			RuntimeReadinessStatus:                      runtimeReadinessStatus,
			RuntimeReadinessFindingTotal:                payloadInt(payload, "runtime_readiness_finding_total"),
			RuntimeReadinessBlockingTotal:               payloadInt(payload, "runtime_readiness_blocking_total"),
			RuntimeReadinessDegradedTotal:               payloadInt(payload, "runtime_readiness_degraded_total"),
			RuntimePrimaryDomain:                        payloadString(payload, "runtime_primary_domain"),
			RuntimePrimaryCode:                          payloadString(payload, "runtime_primary_code"),
			RuntimePrimarySource:                        payloadString(payload, "runtime_primary_source"),
			RuntimePrimaryConflictTotal:                 payloadInt(payload, "runtime_primary_conflict_total"),
			RuntimeSecondaryReasonCodes:                 payloadStringSlice(payload, "runtime_secondary_reason_codes"),
			RuntimeSecondaryReasonCount:                 payloadInt(payload, "runtime_secondary_reason_count"),
			RuntimeArbitrationRuleVersion:               payloadString(payload, "runtime_arbitration_rule_version"),
			RuntimeArbitrationRuleRequestedVersion:      payloadString(payload, "runtime_arbitration_rule_requested_version"),
			RuntimeArbitrationRuleEffectiveVersion:      payloadString(payload, "runtime_arbitration_rule_effective_version"),
			RuntimeArbitrationRuleVersionSource:         payloadString(payload, "runtime_arbitration_rule_version_source"),
			RuntimeArbitrationRulePolicyAction:          payloadString(payload, "runtime_arbitration_rule_policy_action"),
			RuntimeArbitrationRuleUnsupportedTotal:      payloadInt(payload, "runtime_arbitration_rule_unsupported_total"),
			RuntimeArbitrationRuleMismatchTotal:         payloadInt(payload, "runtime_arbitration_rule_mismatch_total"),
			RuntimeRemediationHintCode:                  payloadString(payload, "runtime_remediation_hint_code"),
			RuntimeRemediationHintDomain:                payloadString(payload, "runtime_remediation_hint_domain"),
			RuntimeReadinessPrimaryCode:                 payloadString(payload, "runtime_readiness_primary_code"),
			RuntimeReadinessAdmissionTotal:              payloadInt(payload, "runtime_readiness_admission_total"),
			RuntimeReadinessAdmissionBlockedTotal:       payloadInt(payload, "runtime_readiness_admission_blocked_total"),
			RuntimeReadinessAdmissionDegradedAllowTotal: payloadInt(payload, "runtime_readiness_admission_degraded_allow_total"),
			RuntimeReadinessAdmissionBypassTotal:        payloadInt(payload, "runtime_readiness_admission_bypass_total"),
			RuntimeReadinessAdmissionMode:               payloadString(payload, "runtime_readiness_admission_mode"),
			RuntimeReadinessAdmissionPrimaryCode:        payloadString(payload, "runtime_readiness_admission_primary_code"),
			TraceExportStatus:                           payloadString(payload, "trace_export_status"),
			TraceSchemaVersion:                          payloadString(payload, "trace_schema_version"),
			EvalSuiteID:                                 payloadString(payload, "eval_suite_id"),
			EvalSummary:                                 evalSummary,
			EvalExecutionMode:                           payloadString(payload, "eval_execution_mode"),
			EvalJobID:                                   payloadString(payload, "eval_job_id"),
			EvalShardTotal:                              payloadInt(payload, "eval_shard_total"),
			EvalResumeCount:                             payloadInt(payload, "eval_resume_count"),
			InferentialAdvisoryStatus:                   inferentialAdvisory.Status,
			InferentialAdvisoryScore:                    inferentialAdvisory.Score,
			InferentialAdvisorySignals:                  inferentialAdvisory.Signals,
			InferentialAdvisoryReasons:                  inferentialAdvisory.Reasons,
			BudgetSnapshot:                              budgetSnapshot,
			BudgetDecision:                              budgetDecision,
			DegradeAction:                               payloadString(payload, "degrade_action"),
			PolicyPrecedenceVersion:                     payloadString(payload, "policy_precedence_version"),
			WinnerStage:                                 payloadString(payload, "winner_stage"),
			DenySource:                                  payloadString(payload, "deny_source"),
			TieBreakReason:                              payloadString(payload, "tie_break_reason"),
			PolicyDecisionPath:                          payloadPolicyDecisionPath(payload, "policy_decision_path"),
			AdapterAllowlistDecision:                    payloadString(payload, "adapter_allowlist_decision"),
			AdapterAllowlistBlockTotal:                  payloadInt(payload, "adapter_allowlist_block_total"),
			AdapterAllowlistPrimaryCode:                 payloadString(payload, "adapter_allowlist_primary_code"),
			AdapterHealthStatus:                         payloadString(payload, "adapter_health_status"),
			AdapterHealthProbeTotal:                     payloadInt(payload, "adapter_health_probe_total"),
			AdapterHealthDegradedTotal:                  payloadInt(payload, "adapter_health_degraded_total"),
			AdapterHealthUnavailableTotal:               payloadInt(payload, "adapter_health_unavailable_total"),
			AdapterHealthPrimaryCode:                    payloadString(payload, "adapter_health_primary_code"),
			AdapterHealthBackoffAppliedTotal:            payloadInt(payload, "adapter_health_backoff_applied_total"),
			AdapterHealthCircuitOpenTotal:               payloadInt(payload, "adapter_health_circuit_open_total"),
			AdapterHealthCircuitHalfOpenTotal:           payloadInt(payload, "adapter_health_circuit_half_open_total"),
			AdapterHealthCircuitRecoverTotal:            payloadInt(payload, "adapter_health_circuit_recover_total"),
			AdapterHealthCircuitState:                   payloadString(payload, "adapter_health_circuit_state"),
			AdapterHealthGovernancePrimaryCode:          payloadString(payload, "adapter_health_governance_primary_code"),
			EffectiveOperationProfile:                   payloadString(payload, "effective_operation_profile"),
			TimeoutResolutionSource:                     payloadString(payload, "timeout_resolution_source"),
			TimeoutResolutionTrace:                      payloadString(payload, "timeout_resolution_trace"),
			TimeoutParentBudgetClampTotal:               payloadInt(payload, "timeout_parent_budget_clamp_total"),
			TimeoutParentBudgetRejectTotal:              payloadInt(payload, "timeout_parent_budget_reject_total"),
			DiagnosticsCardinalityBudgetHitTotal:        payloadInt(payload, "diagnostics_cardinality_budget_hit_total"),
			DiagnosticsCardinalityTruncatedTotal:        payloadInt(payload, "diagnostics_cardinality_truncated_total"),
			DiagnosticsCardinalityFailFastRejectTotal:   payloadInt(payload, "diagnostics_cardinality_fail_fast_reject_total"),
			DiagnosticsCardinalityOverflowPolicy:        payloadString(payload, "diagnostics_cardinality_overflow_policy"),
			DiagnosticsCardinalityTruncatedFieldSummary: payloadString(payload, "diagnostics_cardinality_truncated_field_summary"),
			GateChecks:                                  payloadInt(payload, "gate_checks"),
			GateDeniedCount:                             payloadInt(payload, "gate_denied_count"),
			GateTimeoutCount:                            payloadInt(payload, "gate_timeout_count"),
			GateRuleHitCount:                            payloadInt(payload, "gate_rule_hit_count"),
			GateRuleLastID:                              payloadString(payload, "gate_rule_last_id"),
			AwaitCount:                                  payloadInt(payload, "await_count"),
			ResumeCount:                                 payloadInt(payload, "resume_count"),
			CancelByUserCount:                           payloadInt(payload, "cancel_by_user_count"),
			CancelPropagated:                            payloadInt(payload, "cancel_propagated_count"),
			BackpressureDrop:                            payloadInt(payload, "backpressure_drop_count"),
			BackpressureDropByPhase:                     payloadIntMap(payload, "backpressure_drop_count_by_phase"),
			InflightPeak:                                payloadInt(payload, "inflight_peak"),
			ReactEnabled:                                payloadBool(payload, "react_enabled"),
			ReactIterationTotal:                         payloadInt(payload, "react_iteration_total"),
			ReactToolCallTotal:                          payloadInt(payload, "react_tool_call_total"),
			ReactToolCallBudgetHitTotal:                 payloadInt(payload, "react_tool_call_budget_hit_total"),
			ReactIterationBudgetHitTotal:                payloadInt(payload, "react_iteration_budget_hit_total"),
			ReactTerminationReason:                      payloadString(payload, "react_termination_reason"),
			ReactStreamDispatchEnabled:                  payloadBool(payload, "react_stream_dispatch_enabled"),
			ReactPlanID:                                 payloadString(payload, "react_plan_id"),
			ReactPlanVersion:                            payloadInt(payload, "react_plan_version"),
			ReactPlanChangeTotal:                        payloadInt(payload, "react_plan_change_total"),
			ReactPlanLastAction:                         normalizeReactPlanAction(payloadString(payload, "react_plan_last_action")),
			ReactPlanChangeReason:                       payloadString(payload, "react_plan_change_reason"),
			ReactPlanRecoverCount:                       payloadInt(payload, "react_plan_recover_count"),
			ReactPlanHookStatus:                         normalizeReactPlanHookStatus(payloadString(payload, "react_plan_hook_status")),
			RealtimeProtocolVersion:                     payloadString(payload, "realtime_protocol_version"),
			RealtimeSessionID:                           payloadString(payload, "realtime_session_id"),
			RealtimeEventSeqMax:                         payloadInt64(payload, "realtime_event_seq_max"),
			RealtimeInterruptTotal:                      payloadInt(payload, "realtime_interrupt_total"),
			RealtimeResumeTotal:                         payloadInt(payload, "realtime_resume_total"),
			RealtimeResumeSource:                        payloadString(payload, "realtime_resume_source"),
			RealtimeResumeCursor:                        payloadString(payload, "realtime_resume_cursor"),
			RealtimeIdempotencyDedupTotal:               payloadInt(payload, "realtime_idempotency_dedup_total"),
			RealtimeLastErrorCode:                       payloadString(payload, "realtime_last_error_code"),
			HooksEnabled:                                payloadBool(payload, "hooks_enabled"),
			HooksFailMode:                               normalizeHooksFailMode(payloadString(payload, "hooks_fail_mode")),
			HooksPhases:                                 payloadStringSliceCSV(payload, "hooks_phases"),
			ToolMiddlewareEnabled:                       payloadBool(payload, "tool_middleware_enabled"),
			ToolMiddlewareFailMode:                      normalizeToolMiddlewareFailMode(payloadString(payload, "tool_middleware_fail_mode")),
			SkillDiscoveryMode:                          normalizeSkillDiscoveryMode(payloadString(payload, "skill_discovery_mode")),
			SkillDiscoveryRoots:                         payloadStringSlice(payload, "skill_discovery_roots"),
			SkillPreprocessEnabled:                      payloadBool(payload, "skill_preprocess_enabled"),
			SkillPreprocessPhase:                        normalizeSkillPreprocessPhase(payloadString(payload, "skill_preprocess_phase")),
			SkillPreprocessFailMode:                     normalizeSkillPreprocessFailMode(payloadString(payload, "skill_preprocess_fail_mode")),
			SkillPreprocessStatus:                       normalizeSkillPreprocessStatus(payloadString(payload, "skill_preprocess_status")),
			SkillPreprocessReasonCode:                   normalizeSkillPreprocessReasonCode(payloadString(payload, "skill_preprocess_reason_code")),
			SkillPreprocessSpecCount:                    payloadInt(payload, "skill_preprocess_spec_count"),
			SkillBundlePromptMode:                       normalizeSkillBundlePromptMode(payloadString(payload, "skill_bundle_prompt_mode")),
			SkillBundleWhitelistMode:                    normalizeSkillBundleWhitelistMode(payloadString(payload, "skill_bundle_whitelist_mode")),
			SkillBundleConflictPolicy:                   normalizeSkillBundleConflictPolicy(payloadString(payload, "skill_bundle_conflict_policy")),
			SkillBundlePromptTotal:                      payloadInt(payload, "skill_bundle_prompt_total"),
			SkillBundleWhitelistTotal:                   payloadInt(payload, "skill_bundle_whitelist_total"),
			SkillBundleWhitelistRejectedTotal:           payloadInt(payload, "skill_bundle_whitelist_rejected_total"),
		})
	case "skill.discovered":
		r.manager.RecordSkill(runtimediag.SkillRecord{
			Time:      eventTime(ev.Time),
			RunID:     ev.RunID,
			Action:    "discover",
			Status:    "success",
			LatencyMs: payloadInt64(payload, "latency_ms"),
			Payload:   payload,
		})
	case "skill.warning":
		action := payloadString(payload, "action")
		if action == "" {
			action = "compile"
		}
		errorClass := payloadString(payload, "error_class")
		if errorClass == "" {
			errorClass = string(types.ErrSkill)
		}
		r.manager.RecordSkill(runtimediag.SkillRecord{
			Time:       eventTime(ev.Time),
			RunID:      ev.RunID,
			SkillName:  payloadString(payload, "name"),
			Action:     action,
			Status:     payloadOrDefault(payload, "status", "warning"),
			LatencyMs:  payloadInt64(payload, "latency_ms"),
			ErrorClass: errorClass,
			Payload:    payload,
		})
	case "skill.loaded":
		action := payloadString(payload, "action")
		if action == "" {
			action = "compile"
		}
		r.manager.RecordSkill(runtimediag.SkillRecord{
			Time:      eventTime(ev.Time),
			RunID:     ev.RunID,
			SkillName: payloadString(payload, "name"),
			Action:    action,
			Status:    payloadOrDefault(payload, "status", "success"),
			LatencyMs: payloadInt64(payload, "latency_ms"),
			Payload:   payload,
		})
	}
	if r.exporterRuntime != nil {
		exportCfg := r.manager.EffectiveConfig().Runtime.Observability.Export
		r.exporterRuntime.HandleEvent(exportCfg, types.Event{
			Version:   strings.TrimSpace(ev.Version),
			Type:      strings.TrimSpace(ev.Type),
			RunID:     strings.TrimSpace(ev.RunID),
			Iteration: ev.Iteration,
			Time:      eventTime(ev.Time),
			Payload:   payload,
		})
	}
}

func payloadString(m map[string]any, key string) string {
	if len(m) == 0 {
		return ""
	}
	raw, ok := m[key]
	if !ok {
		return ""
	}
	s, _ := raw.(string)
	return strings.TrimSpace(s)
}

func payloadHasKey(m map[string]any, key string) bool {
	if len(m) == 0 {
		return false
	}
	_, ok := m[key]
	return ok
}

func payloadStringCompat(m map[string]any, primary string, legacy string) string {
	if payloadHasKey(m, primary) {
		return payloadString(m, primary)
	}
	return payloadString(m, legacy)
}

func payloadInt64(m map[string]any, key string) int64 {
	if len(m) == 0 {
		return 0
	}
	raw, ok := m[key]
	if !ok {
		return 0
	}
	switch tv := raw.(type) {
	case int64:
		return tv
	case int:
		return int64(tv)
	case float64:
		return int64(tv)
	default:
		return 0
	}
}

func payloadInt(m map[string]any, key string) int {
	return int(payloadInt64(m, key))
}

func payloadIntCompat(m map[string]any, primary string, legacy string) int {
	if payloadHasKey(m, primary) {
		return payloadInt(m, primary)
	}
	return payloadInt(m, legacy)
}

func payloadFloat64(m map[string]any, key string) float64 {
	if len(m) == 0 {
		return 0
	}
	raw, ok := m[key]
	if !ok {
		return 0
	}
	switch tv := raw.(type) {
	case float64:
		return tv
	case float32:
		return float64(tv)
	case int:
		return float64(tv)
	case int64:
		return float64(tv)
	default:
		return 0
	}
}

func payloadFloat64Compat(m map[string]any, primary string, legacy string) float64 {
	if payloadHasKey(m, primary) {
		return payloadFloat64(m, primary)
	}
	return payloadFloat64(m, legacy)
}

func payloadInt64Map(m map[string]any, key string) map[string]int64 {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	out := map[string]int64{}
	switch src := raw.(type) {
	case map[string]any:
		for k, v := range src {
			switch tv := v.(type) {
			case int64:
				out[k] = tv
			case int:
				out[k] = int64(tv)
			case float64:
				out[k] = int64(tv)
			}
		}
	case map[string]int64:
		for k, v := range src {
			out[k] = v
		}
	case map[string]int:
		for k, v := range src {
			out[k] = int64(v)
		}
	default:
		return nil
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func payloadIntMap(m map[string]any, key string) map[string]int {
	in := payloadInt64Map(m, key)
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]int, len(in))
	for k, v := range in {
		out[k] = int(v)
	}
	return out
}

func payloadInt64MapCompat(m map[string]any, primary string, legacy string) map[string]int64 {
	if payloadHasKey(m, primary) {
		return payloadInt64Map(m, primary)
	}
	return payloadInt64Map(m, legacy)
}

func payloadIntMapCompat(m map[string]any, primary string, legacy string) map[string]int {
	if payloadHasKey(m, primary) {
		return payloadIntMap(m, primary)
	}
	return payloadIntMap(m, legacy)
}

func payloadAnyMap(m map[string]any, key string) map[string]any {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok || raw == nil {
		return nil
	}
	switch value := raw.(type) {
	case map[string]any:
		return cloneAnyMap(value)
	default:
		blob, err := json.Marshal(raw)
		if err != nil {
			return nil
		}
		var decoded map[string]any
		if err := json.Unmarshal(blob, &decoded); err != nil {
			return nil
		}
		return cloneAnyMap(decoded)
	}
}

type inferentialAdvisory struct {
	Status  string
	Score   float64
	Signals map[string]float64
	Reasons []string
}

func buildInferentialAdvisory(
	evalCfg runtimeconfig.RuntimeEvalAgentConfig,
	evalSummary map[string]any,
	readinessStatus string,
	budgetDecision string,
	decision string,
) inferentialAdvisory {
	signals := map[string]float64{}
	reasonSet := map[string]struct{}{}
	addSignal := func(key string, value float64) {
		key = strings.TrimSpace(key)
		if key == "" {
			return
		}
		signals[key] = clampInferentialSignal(value)
	}
	addReason := func(code string) {
		code = strings.TrimSpace(code)
		if code == "" {
			return
		}
		reasonSet[code] = struct{}{}
	}

	if rate, ok := evalSummaryMetricRate(evalSummary, "task_success"); ok {
		addSignal("task_success_rate", rate)
		if evalCfg.Enabled && rate < evalCfg.TaskSuccessThreshold {
			addReason("eval.task_success_below_threshold")
		}
	}
	if rate, ok := evalSummaryMetricRate(evalSummary, "tool_correctness"); ok {
		addSignal("tool_correctness_rate", rate)
		if evalCfg.Enabled && rate < evalCfg.ToolCorrectnessThreshold {
			addReason("eval.tool_correctness_below_threshold")
		}
	}
	if rate, ok := evalSummaryMetricRate(evalSummary, "deny_intercept"); ok {
		addSignal("deny_intercept_rate", rate)
		if evalCfg.Enabled && rate < evalCfg.DenyInterceptAccuracyThreshold {
			addReason("eval.deny_intercept_below_threshold")
		}
	}
	if within, ok := evalSummaryCostLatencyBool(evalSummary, "cost_within_budget"); ok {
		if within {
			addSignal("cost_within_budget", 1)
		} else {
			addSignal("cost_within_budget", 0)
			if evalCfg.Enabled {
				addReason("eval.cost_budget_exceeded")
			}
		}
	}
	if within, ok := evalSummaryCostLatencyBool(evalSummary, "latency_within_slo"); ok {
		if within {
			addSignal("latency_within_slo", 1)
		} else {
			addSignal("latency_within_slo", 0)
			if evalCfg.Enabled {
				addReason("eval.latency_budget_exceeded")
			}
		}
	}

	normalizedReadiness := strings.ToLower(strings.TrimSpace(readinessStatus))
	switch normalizedReadiness {
	case "degraded":
		addSignal("runtime_readiness_degraded", 1)
		addReason("runtime.readiness.degraded")
	case "blocked":
		addSignal("runtime_readiness_blocked", 1)
		addReason("runtime.readiness.blocked")
	}

	normalizedBudgetDecision := strings.ToLower(strings.TrimSpace(budgetDecision))
	switch normalizedBudgetDecision {
	case string(runtimeconfig.RuntimeAdmissionBudgetDecisionDeny):
		addSignal("runtime_admission_budget_deny", 1)
		addReason("runtime.admission.budget_deny")
	case string(runtimeconfig.RuntimeAdmissionBudgetDecisionDegrade):
		addSignal("runtime_admission_budget_degrade", 1)
		addReason("runtime.admission.budget_degrade")
	}

	normalizedDecision := strings.ToLower(strings.TrimSpace(decision))
	if normalizedDecision == "deny" {
		addSignal("runtime_policy_decision_deny", 1)
		addReason("runtime.policy.deny")
	}

	score := 1.0
	if len(signals) > 0 {
		total := 0.0
		for _, value := range signals {
			total += clampInferentialSignal(value)
		}
		score = total / float64(len(signals))
	}

	reasons := make([]string, 0, len(reasonSet))
	for code := range reasonSet {
		reasons = append(reasons, code)
	}
	sort.Strings(reasons)
	if len(reasons) == 0 {
		reasons = nil
	}
	if len(signals) == 0 {
		signals = nil
	}

	var status string
	switch {
	case len(reasons) == 0:
		status = "healthy"
	case normalizedDecision == "deny" || normalizedBudgetDecision == string(runtimeconfig.RuntimeAdmissionBudgetDecisionDeny) || normalizedReadiness == "blocked":
		status = "critical"
	default:
		status = "watch"
	}

	return inferentialAdvisory{
		Status:  status,
		Score:   clampInferentialSignal(score),
		Signals: signals,
		Reasons: reasons,
	}
}

func evalSummaryMetricRate(evalSummary map[string]any, metric string) (float64, bool) {
	metricMap, ok := evalSummaryChildMap(evalSummary, metric)
	if !ok {
		return 0, false
	}
	if value, ok := metricMap["rate"]; ok {
		if parsed, ok := anyFloat64(value); ok {
			return clampInferentialSignal(parsed), true
		}
	}
	if value, ok := metricMap["pass_rate"]; ok {
		if parsed, ok := anyFloat64(value); ok {
			return clampInferentialSignal(parsed), true
		}
	}
	return 0, false
}

func evalSummaryCostLatencyBool(evalSummary map[string]any, key string) (bool, bool) {
	costLatency, ok := evalSummaryChildMap(evalSummary, "cost_latency")
	if !ok {
		return false, false
	}
	raw, ok := costLatency[key]
	if !ok {
		return false, false
	}
	return anyBool(raw)
}

func evalSummaryChildMap(evalSummary map[string]any, key string) (map[string]any, bool) {
	if len(evalSummary) == 0 {
		return nil, false
	}
	raw, ok := evalSummary[key]
	if !ok || raw == nil {
		return nil, false
	}
	typed, ok := raw.(map[string]any)
	if !ok {
		return nil, false
	}
	return typed, true
}

func anyFloat64(raw any) (float64, bool) {
	switch value := raw.(type) {
	case float64:
		return value, true
	case float32:
		return float64(value), true
	case int:
		return float64(value), true
	case int8:
		return float64(value), true
	case int16:
		return float64(value), true
	case int32:
		return float64(value), true
	case int64:
		return float64(value), true
	case uint:
		return float64(value), true
	case uint8:
		return float64(value), true
	case uint16:
		return float64(value), true
	case uint32:
		return float64(value), true
	case uint64:
		return float64(value), true
	case json.Number:
		parsed, err := value.Float64()
		if err != nil {
			return 0, false
		}
		return parsed, true
	default:
		return 0, false
	}
}

func anyBool(raw any) (bool, bool) {
	switch value := raw.(type) {
	case bool:
		return value, true
	case string:
		switch strings.ToLower(strings.TrimSpace(value)) {
		case "true":
			return true, true
		case "false":
			return false, true
		default:
			return false, false
		}
	default:
		return false, false
	}
}

func clampInferentialSignal(value float64) float64 {
	switch {
	case value < 0:
		return 0
	case value > 1:
		return 1
	default:
		return value
	}
}

func cloneAnyMap(in map[string]any) map[string]any {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]any, len(in))
	for key, value := range in {
		if child, ok := value.(map[string]any); ok {
			out[key] = cloneAnyMap(child)
			continue
		}
		out[key] = value
	}
	return out
}

func payloadStringSlice(m map[string]any, key string) []string {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	out := []string{}
	switch src := raw.(type) {
	case []string:
		for i := range src {
			item := strings.TrimSpace(src[i])
			if item == "" {
				continue
			}
			out = append(out, item)
		}
	case []any:
		for i := range src {
			item, ok := src[i].(string)
			if !ok {
				continue
			}
			item = strings.TrimSpace(item)
			if item == "" {
				continue
			}
			out = append(out, item)
		}
	default:
		return nil
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func payloadPolicyDecisionPath(m map[string]any, key string) []runtimediag.RuntimePolicyDecisionPathEntry {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	out := make([]runtimediag.RuntimePolicyDecisionPathEntry, 0)
	appendItem := func(stage, code, source, decision string) {
		entry := runtimediag.RuntimePolicyDecisionPathEntry{
			Stage:    strings.ToLower(strings.TrimSpace(stage)),
			Code:     strings.TrimSpace(code),
			Source:   strings.ToLower(strings.TrimSpace(source)),
			Decision: strings.ToLower(strings.TrimSpace(decision)),
		}
		if entry.Stage == "" {
			return
		}
		out = append(out, entry)
	}
	switch src := raw.(type) {
	case []runtimeconfig.RuntimePolicyCandidate:
		for i := range src {
			appendItem(src[i].Stage, src[i].Code, src[i].Source, src[i].Decision)
		}
	case []runtimediag.RuntimePolicyDecisionPathEntry:
		for i := range src {
			appendItem(src[i].Stage, src[i].Code, src[i].Source, src[i].Decision)
		}
	case []any:
		for i := range src {
			switch item := src[i].(type) {
			case map[string]any:
				appendItem(
					payloadString(item, "stage"),
					payloadString(item, "code"),
					payloadString(item, "source"),
					payloadString(item, "decision"),
				)
			case runtimeconfig.RuntimePolicyCandidate:
				appendItem(item.Stage, item.Code, item.Source, item.Decision)
			case runtimediag.RuntimePolicyDecisionPathEntry:
				appendItem(item.Stage, item.Code, item.Source, item.Decision)
			}
		}
	default:
		return nil
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func payloadStringSliceCSV(m map[string]any, key string) []string {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	switch src := raw.(type) {
	case string:
		parts := strings.Split(src, ",")
		out := make([]string, 0, len(parts))
		for i := range parts {
			item := strings.TrimSpace(parts[i])
			if item == "" {
				continue
			}
			out = append(out, item)
		}
		if len(out) == 0 {
			return nil
		}
		return out
	default:
		return payloadStringSlice(m, key)
	}
}

func payloadOrDefault(m map[string]any, key, fallback string) string {
	v := payloadString(m, key)
	if v == "" {
		return fallback
	}
	return v
}

func payloadStringOrFallback(m map[string]any, key, fallback string) string {
	v := payloadString(m, key)
	if v == "" {
		return strings.TrimSpace(fallback)
	}
	return v
}

func payloadIntOrFallback(m map[string]any, key string, fallback int) int {
	if len(m) == 0 {
		return fallback
	}
	if _, ok := m[key]; !ok {
		return fallback
	}
	return payloadInt(m, key)
}

func payloadBool(m map[string]any, key string) bool {
	if len(m) == 0 {
		return false
	}
	raw, ok := m[key]
	if !ok {
		return false
	}
	v, _ := raw.(bool)
	return v
}

func payloadBoolCompat(m map[string]any, primary string, legacy string) bool {
	if payloadHasKey(m, primary) {
		return payloadBool(m, primary)
	}
	return payloadBool(m, legacy)
}

func eventTime(ts time.Time) time.Time {
	if ts.IsZero() {
		return time.Now()
	}
	return ts
}

func shouldAutoGenerateDiagnosticsBundle(
	manager *runtimeconfig.Manager,
	bundleTotal int,
	bundleStatus string,
	bundleSchemaVersion string,
	bundleReasonCode string,
) bool {
	if manager == nil {
		return false
	}
	cfg := manager.EffectiveConfig().Runtime.Diagnostics.Bundle
	if !cfg.Enabled {
		return false
	}
	if bundleTotal > 0 {
		return false
	}
	if strings.TrimSpace(bundleStatus) != "" {
		return false
	}
	if strings.TrimSpace(bundleSchemaVersion) != "" {
		return false
	}
	if strings.TrimSpace(bundleReasonCode) != "" {
		return false
	}
	return true
}

func normalizeRuntimeObservabilityExportProfile(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeObservabilityExportProfileOTLP:
		return runtimeconfig.RuntimeObservabilityExportProfileOTLP
	case runtimeconfig.RuntimeObservabilityExportProfileLangfuse:
		return runtimeconfig.RuntimeObservabilityExportProfileLangfuse
	case runtimeconfig.RuntimeObservabilityExportProfileCustom:
		return runtimeconfig.RuntimeObservabilityExportProfileCustom
	case runtimeconfig.RuntimeObservabilityExportProfileNone:
		return runtimeconfig.RuntimeObservabilityExportProfileNone
	default:
		return runtimeconfig.RuntimeObservabilityExportProfileNone
	}
}

func normalizeRuntimeObservabilityExportStatus(raw string, profile string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case RuntimeExportStatusDisabled:
		return RuntimeExportStatusDisabled
	case RuntimeExportStatusSuccess:
		return RuntimeExportStatusSuccess
	case RuntimeExportStatusDegraded:
		return RuntimeExportStatusDegraded
	case RuntimeExportStatusFailed:
		return RuntimeExportStatusFailed
	default:
		if normalizeRuntimeObservabilityExportProfile(profile) == runtimeconfig.RuntimeObservabilityExportProfileNone {
			return RuntimeExportStatusDisabled
		}
		return RuntimeExportStatusSuccess
	}
}

func normalizeRuntimeDiagnosticsBundleStatus(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeDiagnosticsBundleStatusDisabled:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusDisabled
	case runtimeconfig.RuntimeDiagnosticsBundleStatusSuccess:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusSuccess
	case runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded
	case runtimeconfig.RuntimeDiagnosticsBundleStatusFailed:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusFailed
	default:
		return ""
	}
}

func normalizeRuntimeDiagnosticsBundleReasonCode(raw string, status string) string {
	normalizedStatus := normalizeRuntimeDiagnosticsBundleStatus(status)
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		if normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusFailed || normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded {
			return runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown
		}
		return ""
	case runtimeconfig.RuntimeDiagnosticsBundleReasonOutputUnavailable:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonOutputUnavailable
	case runtimeconfig.RuntimeDiagnosticsBundleReasonPolicyInvalid:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonPolicyInvalid
	case runtimeconfig.RuntimeDiagnosticsBundleReasonMaxSizeExceeded:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonMaxSizeExceeded
	case runtimeconfig.RuntimeDiagnosticsBundleReasonSectionMissing:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonSectionMissing
	case runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown
	default:
		if normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusFailed || normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded {
			return runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown
		}
		return ""
	}
}

func normalizeRuntimeDiagnosticsBundleSchemaVersion(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		return ""
	case runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1:
		return runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1
	default:
		return runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1
	}
}

func normalizeReactPlanAction(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "create":
		return "create"
	case "revise":
		return "revise"
	case "complete":
		return "complete"
	case "recover":
		return "recover"
	default:
		return ""
	}
}

func normalizeReactPlanHookStatus(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "ok":
		return "ok"
	case "degraded":
		return "degraded"
	case "failed":
		return "failed"
	case "disabled":
		return "disabled"
	default:
		return ""
	}
}

func normalizeHooksFailMode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeHooksFailModeFailFast:
		return runtimeconfig.RuntimeHooksFailModeFailFast
	case runtimeconfig.RuntimeHooksFailModeDegrade:
		return runtimeconfig.RuntimeHooksFailModeDegrade
	default:
		return ""
	}
}

func normalizeToolMiddlewareFailMode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeToolMiddlewareFailModeFailFast:
		return runtimeconfig.RuntimeToolMiddlewareFailModeFailFast
	case runtimeconfig.RuntimeToolMiddlewareFailModeDegrade:
		return runtimeconfig.RuntimeToolMiddlewareFailModeDegrade
	default:
		return ""
	}
}

func normalizeSkillDiscoveryMode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeSkillDiscoveryModeAgentsMD:
		return runtimeconfig.RuntimeSkillDiscoveryModeAgentsMD
	case runtimeconfig.RuntimeSkillDiscoveryModeFolder:
		return runtimeconfig.RuntimeSkillDiscoveryModeFolder
	case runtimeconfig.RuntimeSkillDiscoveryModeHybrid:
		return runtimeconfig.RuntimeSkillDiscoveryModeHybrid
	default:
		return ""
	}
}

func normalizeSkillPreprocessPhase(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeSkillPreprocessPhaseBeforeRunStream:
		return runtimeconfig.RuntimeSkillPreprocessPhaseBeforeRunStream
	default:
		return ""
	}
}

func normalizeSkillPreprocessFailMode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeSkillPreprocessFailModeFailFast:
		return runtimeconfig.RuntimeSkillPreprocessFailModeFailFast
	case runtimeconfig.RuntimeSkillPreprocessFailModeDegrade:
		return runtimeconfig.RuntimeSkillPreprocessFailModeDegrade
	default:
		return ""
	}
}

func normalizeSkillPreprocessStatus(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "success":
		return "success"
	case "failed":
		return "failed"
	case "degraded":
		return "degraded"
	case "skipped":
		return "skipped"
	default:
		return ""
	}
}

func normalizeSkillPreprocessReasonCode(raw string) string {
	value := strings.ToLower(strings.TrimSpace(raw))
	switch value {
	case "":
		return ""
	case "skill_preprocess_failed",
		"skill_bundle_prompt_conflict",
		"skill_bundle_whitelist_conflict",
		"skill_bundle_whitelist_exceeds_sandbox",
		"skill_bundle_whitelist_exceeds_adapter_allowlist",
		"skill_bundle_whitelist_invalid_tool",
		"skill_bundle_whitelist_violation":
		return value
	default:
		// Drift guard: unknown synonyms collapse to canonical fallback.
		return "skill_preprocess_failed"
	}
}

func normalizeSkillBundlePromptMode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeSkillBundleMappingPromptModeDisabled:
		return runtimeconfig.RuntimeSkillBundleMappingPromptModeDisabled
	case runtimeconfig.RuntimeSkillBundleMappingPromptModeAppend:
		return runtimeconfig.RuntimeSkillBundleMappingPromptModeAppend
	default:
		return ""
	}
}

func normalizeSkillBundleWhitelistMode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeSkillBundleMappingWhitelistModeDisabled:
		return runtimeconfig.RuntimeSkillBundleMappingWhitelistModeDisabled
	case runtimeconfig.RuntimeSkillBundleMappingWhitelistModeMerge:
		return runtimeconfig.RuntimeSkillBundleMappingWhitelistModeMerge
	default:
		return ""
	}
}

func normalizeSkillBundleConflictPolicy(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeSkillBundleMappingConflictPolicyFailFast:
		return runtimeconfig.RuntimeSkillBundleMappingConflictPolicyFailFast
	case runtimeconfig.RuntimeSkillBundleMappingConflictPolicyFirstWin:
		return runtimeconfig.RuntimeSkillBundleMappingConflictPolicyFirstWin
	default:
		return ""
	}
}

func normalizeStateSnapshotVersion(raw string) string {
	value := strings.ToLower(strings.TrimSpace(raw))
	switch value {
	case "", "state_session_snapshot.v1":
		return value
	default:
		// Additive+nullable contract: preserve unknown snapshot version strings for forward compatibility.
		return value
	}
}

func normalizeStateRestoreAction(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		return ""
	case "strict_exact_restore":
		return "strict_exact_restore"
	case "compatible_exact_restore":
		return "compatible_exact_restore"
	case "compatible_bounded_restore":
		return "compatible_bounded_restore"
	case "idempotent_noop":
		return "idempotent_noop"
	default:
		// Drift guard: unknown aliases collapse to canonical bounded restore action.
		return "compatible_bounded_restore"
	}
}

func normalizeStateRestoreConflictCode(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		return ""
	case "state_snapshot_invalid_payload",
		"state_snapshot_restore_mode_invalid",
		"state_snapshot_strict_incompatible",
		"state_snapshot_compat_window_exceeded",
		"state_snapshot_operation_conflict",
		"state_snapshot_digest_mismatch",
		"snapshot_recovery_boundary_violation",
		"snapshot_scheduler_conflict",
		"snapshot_mailbox_conflict",
		"snapshot_memory_contract_mismatch",
		"snapshot_memory_lifecycle_mismatch",
		"snapshot_memory_search_policy_mismatch",
		"snapshot_memory_retrieval_quality_drift":
		return strings.ToLower(strings.TrimSpace(raw))
	default:
		// Drift guard: unknown aliases collapse to canonical snapshot conflict code.
		return "state_snapshot_invalid_payload"
	}
}

func normalizeStateRestoreSource(raw string) string {
	return strings.ToLower(strings.TrimSpace(raw))
}

var _ types.EventHandler = (*RuntimeRecorder)(nil)
