package event

import (
	"context"
	"strings"
	"time"

	"github.com/FelixSeptem/baymax/core/types"
	runtimeconfig "github.com/FelixSeptem/baymax/runtime/config"
	runtimediag "github.com/FelixSeptem/baymax/runtime/diagnostics"
)

type RuntimeRecorder struct {
	manager         *runtimeconfig.Manager
	exporterRuntime *runtimeExporterRuntime
}

type RuntimeRecorderOption func(*runtimeRecorderOptionSet)

type runtimeRecorderOptionSet struct {
	exporterResolver RuntimeExporterResolver
	exporterFactory  map[string]RuntimeExporterFactory
}

func WithRuntimeExporterResolver(resolver RuntimeExporterResolver) RuntimeRecorderOption {
	return func(opts *runtimeRecorderOptionSet) {
		if opts == nil || resolver == nil {
			return
		}
		opts.exporterResolver = resolver
	}
}

func WithRuntimeExporterFactory(profile string, factory RuntimeExporterFactory) RuntimeRecorderOption {
	return func(opts *runtimeRecorderOptionSet) {
		if opts == nil || factory == nil {
			return
		}
		normalized := strings.ToLower(strings.TrimSpace(profile))
		if normalized == "" {
			return
		}
		if opts.exporterFactory == nil {
			opts.exporterFactory = map[string]RuntimeExporterFactory{}
		}
		opts.exporterFactory[normalized] = factory
	}
}

func NewRuntimeRecorder(manager *runtimeconfig.Manager, options ...RuntimeRecorderOption) *RuntimeRecorder {
	opts := runtimeRecorderOptionSet{
		exporterFactory: map[string]RuntimeExporterFactory{},
	}
	for i := range options {
		if options[i] == nil {
			continue
		}
		options[i](&opts)
	}
	resolver := opts.exporterResolver
	if resolver == nil {
		resolver = newDefaultRuntimeExporterResolver(opts.exporterFactory)
	}
	return &RuntimeRecorder{
		manager:         manager,
		exporterRuntime: newRuntimeExporterRuntime(resolver),
	}
}

func (r *RuntimeRecorder) ExportSnapshot() RuntimeExportSnapshot {
	if r == nil || r.exporterRuntime == nil {
		return RuntimeExportSnapshot{}
	}
	return r.exporterRuntime.Snapshot()
}

func (r *RuntimeRecorder) Close() {
	if r == nil || r.exporterRuntime == nil {
		return
	}
	r.exporterRuntime.Close()
}

func (r *RuntimeRecorder) OnEvent(ctx context.Context, ev types.Event) {
	if r == nil || r.manager == nil {
		return
	}
	if ctx == nil {
		ctx = context.Background()
	}
	payload := ev.Payload
	if len(payload) > 0 {
		payload = r.manager.RedactPayload(payload)
	}
	switch ev.Type {
	case types.EventTypeActionTimeline:
		if timeline, ok := ParseActionTimeline(types.Event{
			Version:   ev.Version,
			Type:      ev.Type,
			RunID:     ev.RunID,
			Iteration: ev.Iteration,
			Time:      ev.Time,
			Payload:   payload,
		}); ok {
			r.manager.RecordRunTimelineEvent(
				timeline.RunID,
				string(timeline.Phase),
				string(timeline.Status),
				timeline.Sequence,
				timeline.Time,
			)
		}
	case "run.finished":
		errorClass := payloadString(payload, "error_class")
		status := payloadString(payload, "status")
		if status == "" {
			if errorClass != "" {
				status = "failed"
			} else {
				status = "success"
			}
		}
		exportSnapshot := r.ExportSnapshot()
		exportProfile := normalizeRuntimeObservabilityExportProfile(payloadStringOrFallback(payload, "observability_export_profile", exportSnapshot.Profile))
		exportStatus := normalizeRuntimeObservabilityExportStatus(payloadStringOrFallback(payload, "observability_export_status", exportSnapshot.Status), exportProfile)
		bundleTotal := payloadInt(payload, "diagnostics_bundle_total")
		bundleStatus := normalizeRuntimeDiagnosticsBundleStatus(payloadString(payload, "diagnostics_bundle_last_status"))
		bundleReasonCode := normalizeRuntimeDiagnosticsBundleReasonCode(payloadString(payload, "diagnostics_bundle_last_reason_code"), bundleStatus)
		bundleSchemaVersion := normalizeRuntimeDiagnosticsBundleSchemaVersion(payloadString(payload, "diagnostics_bundle_last_schema_version"))
		if shouldAutoGenerateDiagnosticsBundle(r.manager, bundleTotal, bundleStatus, bundleSchemaVersion, bundleReasonCode) {
			result, err := r.manager.GenerateDiagnosticsBundle(ctx, runtimeconfig.DiagnosticsBundleGenerateRequest{
				RunID:              ev.RunID,
				RunFinishedPayload: payload,
			})
			if err != nil {
				code := runtimeconfig.DiagnosticsBundleErrorCode(err)
				if bundleStatus == "" {
					bundleStatus = runtimeconfig.RuntimeDiagnosticsBundleStatusFailed
				}
				if bundleReasonCode == "" {
					bundleReasonCode = normalizeRuntimeDiagnosticsBundleReasonCode(code, bundleStatus)
				}
				if bundleSchemaVersion == "" {
					bundleSchemaVersion = runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1
				}
				if bundleTotal <= 0 {
					bundleTotal = 1
				}
			} else {
				if bundleTotal <= 0 {
					bundleTotal = result.Total
				}
				if bundleStatus == "" {
					bundleStatus = normalizeRuntimeDiagnosticsBundleStatus(result.Status)
				}
				if bundleReasonCode == "" {
					bundleReasonCode = normalizeRuntimeDiagnosticsBundleReasonCode(result.ReasonCode, bundleStatus)
				}
				if bundleSchemaVersion == "" {
					bundleSchemaVersion = normalizeRuntimeDiagnosticsBundleSchemaVersion(result.Manifest.SchemaVersion)
				}
			}
		}
		r.manager.RecordRun(runtimediag.RunRecord{
			Time:                                        ev.Time,
			RunID:                                       ev.RunID,
			Status:                                      status,
			Iterations:                                  ev.Iteration,
			ToolCalls:                                   payloadInt(payload, "tool_calls"),
			LatencyMs:                                   payloadInt64(payload, "latency_ms"),
			ErrorClass:                                  errorClass,
			PolicyKind:                                  payloadString(payload, "policy_kind"),
			NamespaceTool:                               payloadString(payload, "namespace_tool"),
			FilterStage:                                 payloadString(payload, "filter_stage"),
			Decision:                                    payloadString(payload, "decision"),
			ReasonCode:                                  payloadString(payload, "reason_code"),
			Severity:                                    payloadString(payload, "severity"),
			AlertDispatchStatus:                         payloadString(payload, "alert_dispatch_status"),
			AlertDispatchFailureReason:                  payloadString(payload, "alert_dispatch_failure_reason"),
			AlertDeliveryMode:                           payloadString(payload, "alert_delivery_mode"),
			AlertRetryCount:                             payloadInt(payload, "alert_retry_count"),
			AlertQueueDropped:                           payloadBool(payload, "alert_queue_dropped"),
			AlertQueueDropCount:                         payloadInt(payload, "alert_queue_drop_count"),
			AlertCircuitState:                           payloadString(payload, "alert_circuit_state"),
			AlertCircuitOpenReason:                      payloadString(payload, "alert_circuit_open_reason"),
			ModelProvider:                               payloadString(payload, "model_provider"),
			FallbackUsed:                                payloadBool(payload, "fallback_used"),
			FallbackInitial:                             payloadString(payload, "fallback_initial"),
			FallbackPath:                                payloadString(payload, "fallback_path"),
			RequiredCapabilities:                        payloadString(payload, "required_capabilities"),
			FallbackReason:                              payloadString(payload, "fallback_reason"),
			MemoryMode:                                  payloadString(payload, "memory_mode"),
			MemoryProvider:                              payloadString(payload, "memory_provider"),
			MemoryProfile:                               payloadString(payload, "memory_profile"),
			MemoryContractVersion:                       payloadString(payload, "memory_contract_version"),
			MemoryQueryTotal:                            payloadInt(payload, "memory_query_total"),
			MemoryUpsertTotal:                           payloadInt(payload, "memory_upsert_total"),
			MemoryDeleteTotal:                           payloadInt(payload, "memory_delete_total"),
			MemoryErrorTotal:                            payloadInt(payload, "memory_error_total"),
			MemoryFallbackTotal:                         payloadInt(payload, "memory_fallback_total"),
			MemoryFallbackReasonCode:                    payloadString(payload, "memory_fallback_reason_code"),
			MemoryLatencyMsP95:                          payloadInt64(payload, "memory_latency_ms_p95"),
			ObservabilityExportProfile:                  exportProfile,
			ObservabilityExportStatus:                   exportStatus,
			ObservabilityExportErrorTotal:               payloadIntOrFallback(payload, "observability_export_error_total", exportSnapshot.ErrorTotal),
			ObservabilityExportDropTotal:                payloadIntOrFallback(payload, "observability_export_drop_total", exportSnapshot.DropTotal),
			ObservabilityExportQueueDepthPeak:           payloadIntOrFallback(payload, "observability_export_queue_depth_peak", exportSnapshot.QueueDepthPeak),
			DiagnosticsBundleTotal:                      bundleTotal,
			DiagnosticsBundleLastStatus:                 bundleStatus,
			DiagnosticsBundleLastReasonCode:             bundleReasonCode,
			DiagnosticsBundleLastSchemaVersion:          bundleSchemaVersion,
			SandboxMode:                                 payloadString(payload, "sandbox_mode"),
			SandboxBackend:                              payloadString(payload, "sandbox_backend"),
			SandboxProfile:                              payloadString(payload, "sandbox_profile"),
			SandboxSessionMode:                          payloadString(payload, "sandbox_session_mode"),
			SandboxRequiredCapabilities:                 payloadStringSliceCSV(payload, "sandbox_required_capabilities"),
			SandboxDecision:                             payloadString(payload, "sandbox_decision"),
			SandboxReasonCode:                           payloadString(payload, "sandbox_reason_code"),
			SandboxFallbackUsed:                         payloadBool(payload, "sandbox_fallback_used"),
			SandboxFallbackReason:                       payloadString(payload, "sandbox_fallback_reason"),
			SandboxTimeoutTotal:                         payloadInt(payload, "sandbox_timeout_total"),
			SandboxLaunchFailedTotal:                    payloadInt(payload, "sandbox_launch_failed_total"),
			SandboxCapabilityMismatchTotal:              payloadInt(payload, "sandbox_capability_mismatch_total"),
			SandboxQueueWaitMsP95:                       payloadInt64(payload, "sandbox_queue_wait_ms_p95"),
			SandboxExecLatencyMsP95:                     payloadInt64(payload, "sandbox_exec_latency_ms_p95"),
			SandboxExitCodeLast:                         payloadInt(payload, "sandbox_exit_code_last"),
			SandboxOOMTotal:                             payloadInt(payload, "sandbox_oom_total"),
			SandboxResourceCPUMsTotal:                   payloadInt64(payload, "sandbox_resource_cpu_ms_total"),
			SandboxResourceMemoryPeakBytesP95:           payloadInt64(payload, "sandbox_resource_memory_peak_bytes_p95"),
			SandboxRolloutPhase:                         payloadString(payload, "sandbox_rollout_phase"),
			SandboxRolloutEffectiveRatio:                payloadFloat64(payload, "sandbox_rollout_effective_ratio"),
			SandboxHealthBudgetStatus:                   payloadString(payload, "sandbox_health_budget_status"),
			SandboxHealthBudgetBreachTotal:              payloadInt(payload, "sandbox_health_budget_breach_total"),
			SandboxFreezeState:                          payloadBool(payload, "sandbox_freeze_state"),
			SandboxFreezeReasonCode:                     payloadString(payload, "sandbox_freeze_reason_code"),
			SandboxCapacityAction:                       payloadString(payload, "sandbox_capacity_action"),
			SandboxCapacityQueueDepth:                   payloadInt(payload, "sandbox_capacity_queue_depth"),
			SandboxCapacityInflight:                     payloadInt(payload, "sandbox_capacity_inflight"),
			PrefixHash:                                  payloadString(payload, "prefix_hash"),
			AssembleLatencyMs:                           payloadInt64(payload, "assemble_latency_ms"),
			AssembleStatus:                              payloadString(payload, "assemble_status"),
			GuardViolation:                              payloadString(payload, "guard_violation"),
			AssembleStageStatus:                         payloadString(payload, "assemble_stage_status"),
			Stage2SkipReason:                            payloadString(payload, "stage2_skip_reason"),
			Stage2RouterMode:                            payloadString(payload, "stage2_router_mode"),
			Stage2RouterDecision:                        payloadString(payload, "stage2_router_decision"),
			Stage2RouterReason:                          payloadString(payload, "stage2_router_reason"),
			Stage2RouterLatencyMs:                       payloadInt64(payload, "stage2_router_latency_ms"),
			Stage2RouterError:                           payloadString(payload, "stage2_router_error"),
			Stage1LatencyMs:                             payloadInt64(payload, "stage1_latency_ms"),
			Stage2LatencyMs:                             payloadInt64(payload, "stage2_latency_ms"),
			Stage2Provider:                              payloadString(payload, "stage2_provider"),
			Stage2Profile:                               payloadString(payload, "stage2_profile"),
			Stage2TemplateProfile:                       payloadString(payload, "stage2_template_profile"),
			Stage2TemplateResolutionSource:              payloadString(payload, "stage2_template_resolution_source"),
			Stage2HintApplied:                           payloadBool(payload, "stage2_hint_applied"),
			Stage2HintMismatchReason:                    payloadString(payload, "stage2_hint_mismatch_reason"),
			Stage2HitCount:                              payloadInt(payload, "stage2_hit_count"),
			Stage2Source:                                payloadString(payload, "stage2_source"),
			Stage2Reason:                                payloadString(payload, "stage2_reason"),
			Stage2ReasonCode:                            payloadString(payload, "stage2_reason_code"),
			Stage2ErrorLayer:                            payloadString(payload, "stage2_error_layer"),
			CA3PressureZone:                             payloadString(payload, "ca3_pressure_zone"),
			CA3PressureReason:                           payloadString(payload, "ca3_pressure_reason"),
			CA3PressureTrigger:                          payloadString(payload, "ca3_pressure_trigger"),
			CA3ZoneResidencyMs:                          payloadInt64Map(payload, "ca3_zone_residency_ms"),
			CA3TriggerCounts:                            payloadIntMap(payload, "ca3_trigger_counts"),
			CA3CompressionRatio:                         payloadFloat64(payload, "ca3_compression_ratio"),
			CA3SpillCount:                               payloadInt(payload, "ca3_spill_count"),
			CA3SwapBackCount:                            payloadInt(payload, "ca3_swap_back_count"),
			CA3CompactionMode:                           payloadString(payload, "ca3_compaction_mode"),
			CA3CompactionFallback:                       payloadBool(payload, "ca3_compaction_fallback"),
			CA3CompactionFallbackReason:                 payloadString(payload, "ca3_compaction_fallback_reason"),
			CA3CompactionQualityScore:                   payloadFloat64(payload, "ca3_compaction_quality_score"),
			CA3CompactionQualityReason:                  payloadString(payload, "ca3_compaction_quality_reason"),
			CA3CompactionEmbeddingProvider:              payloadString(payload, "ca3_compaction_embedding_provider"),
			CA3CompactionEmbeddingSimilarity:            payloadFloat64(payload, "ca3_compaction_embedding_similarity"),
			CA3CompactionEmbeddingContribution:          payloadFloat64(payload, "ca3_compaction_embedding_contribution"),
			CA3CompactionEmbeddingStatus:                payloadString(payload, "ca3_compaction_embedding_status"),
			CA3CompactionEmbeddingFallbackReason:        payloadString(payload, "ca3_compaction_embedding_fallback_reason"),
			CA3CompactionRerankerUsed:                   payloadBool(payload, "ca3_compaction_reranker_used"),
			CA3CompactionRerankerProvider:               payloadString(payload, "ca3_compaction_reranker_provider"),
			CA3CompactionRerankerModel:                  payloadString(payload, "ca3_compaction_reranker_model"),
			CA3CompactionRerankerThresholdSource:        payloadString(payload, "ca3_compaction_reranker_threshold_source"),
			CA3CompactionRerankerThresholdHit:           payloadBool(payload, "ca3_compaction_reranker_threshold_hit"),
			CA3CompactionRerankerFallbackReason:         payloadString(payload, "ca3_compaction_reranker_fallback_reason"),
			CA3CompactionRerankerProfileVersion:         payloadString(payload, "ca3_compaction_reranker_profile_version"),
			CA3CompactionRerankerRolloutHit:             payloadBool(payload, "ca3_compaction_reranker_rollout_hit"),
			CA3CompactionRerankerThresholdDrift:         payloadFloat64(payload, "ca3_compaction_reranker_threshold_drift"),
			CA3RetainedEvidence:                         payloadInt(payload, "ca3_compaction_retained_evidence_count"),
			RecapStatus:                                 payloadString(payload, "recap_status"),
			TeamID:                                      payloadString(payload, "team_id"),
			TeamStrategy:                                payloadString(payload, "team_strategy"),
			TeamTaskTotal:                               payloadInt(payload, "team_task_total"),
			TeamTaskFailed:                              payloadInt(payload, "team_task_failed"),
			TeamTaskCanceled:                            payloadInt(payload, "team_task_canceled"),
			TeamRemoteTaskTotal:                         payloadInt(payload, "team_remote_task_total"),
			TeamRemoteTaskFailed:                        payloadInt(payload, "team_remote_task_failed"),
			WorkflowID:                                  payloadString(payload, "workflow_id"),
			WorkflowStatus:                              payloadString(payload, "workflow_status"),
			WorkflowStepTotal:                           payloadInt(payload, "workflow_step_total"),
			WorkflowStepFailed:                          payloadInt(payload, "workflow_step_failed"),
			WorkflowRemoteStepTotal:                     payloadInt(payload, "workflow_remote_step_total"),
			WorkflowRemoteStepFailed:                    payloadInt(payload, "workflow_remote_step_failed"),
			WorkflowSubgraphExpansionTotal:              payloadInt(payload, "workflow_subgraph_expansion_total"),
			WorkflowConditionTemplateTotal:              payloadInt(payload, "workflow_condition_template_total"),
			WorkflowGraphCompileFailed:                  payloadBool(payload, "workflow_graph_compile_failed"),
			WorkflowResumeCount:                         payloadInt(payload, "workflow_resume_count"),
			TaskID:                                      payloadString(payload, "task_id"),
			A2ATaskTotal:                                payloadInt(payload, "a2a_task_total"),
			A2ATaskFailed:                               payloadInt(payload, "a2a_task_failed"),
			PeerID:                                      payloadString(payload, "peer_id"),
			A2AErrorLayer:                               payloadString(payload, "a2a_error_layer"),
			A2ADeliveryMode:                             payloadString(payload, "a2a_delivery_mode"),
			A2ADeliveryFallbackUsed:                     payloadBool(payload, "a2a_delivery_fallback_used"),
			A2ADeliveryFallbackReason:                   payloadString(payload, "a2a_delivery_fallback_reason"),
			A2AVersionLocal:                             payloadString(payload, "a2a_version_local"),
			A2AVersionPeer:                              payloadString(payload, "a2a_version_peer"),
			A2AVersionNegotiationResult:                 payloadString(payload, "a2a_version_negotiation_result"),
			A2AAsyncReportTotal:                         payloadInt(payload, "a2a_async_report_total"),
			A2AAsyncReportFailed:                        payloadInt(payload, "a2a_async_report_failed"),
			A2AAsyncReportRetryTotal:                    payloadInt(payload, "a2a_async_report_retry_total"),
			A2AAsyncReportDedupTotal:                    payloadInt(payload, "a2a_async_report_dedup_total"),
			AsyncAwaitTotal:                             payloadInt(payload, "async_await_total"),
			AsyncTimeoutTotal:                           payloadInt(payload, "async_timeout_total"),
			AsyncLateReportTotal:                        payloadInt(payload, "async_late_report_total"),
			AsyncReportDedupTotal:                       payloadInt(payload, "async_report_dedup_total"),
			AsyncReconcilePollTotal:                     payloadInt(payload, "async_reconcile_poll_total"),
			AsyncReconcileTerminalByPollTotal:           payloadInt(payload, "async_reconcile_terminal_by_poll_total"),
			AsyncReconcileErrorTotal:                    payloadInt(payload, "async_reconcile_error_total"),
			AsyncTerminalConflictTotal:                  payloadInt(payload, "async_terminal_conflict_total"),
			ComposerManaged:                             payloadBool(payload, "composer_managed"),
			SchedulerBackend:                            payloadString(payload, "scheduler_backend"),
			SchedulerQoSMode:                            payloadString(payload, "scheduler_qos_mode"),
			SchedulerBackendFallback:                    payloadBool(payload, "scheduler_backend_fallback"),
			SchedulerBackendFallbackReason:              payloadString(payload, "scheduler_backend_fallback_reason"),
			SchedulerQueueTotal:                         payloadInt(payload, "scheduler_queue_total"),
			SchedulerClaimTotal:                         payloadInt(payload, "scheduler_claim_total"),
			SchedulerReclaimTotal:                       payloadInt(payload, "scheduler_reclaim_total"),
			SchedulerPriorityClaimTotal:                 payloadInt(payload, "scheduler_priority_claim_total"),
			SchedulerFairnessYieldTotal:                 payloadInt(payload, "scheduler_fairness_yield_total"),
			SchedulerRetryBackoffTotal:                  payloadInt(payload, "scheduler_retry_backoff_total"),
			SchedulerDeadLetterTotal:                    payloadInt(payload, "scheduler_dead_letter_total"),
			SchedulerDelayedTaskTotal:                   payloadInt(payload, "scheduler_delayed_task_total"),
			SchedulerDelayedClaimTotal:                  payloadInt(payload, "scheduler_delayed_claim_total"),
			SchedulerDelayedWaitMsP95:                   payloadInt64(payload, "scheduler_delayed_wait_ms_p95"),
			TaskBoardManualControlTotal:                 payloadInt(payload, "task_board_manual_control_total"),
			TaskBoardManualControlSuccessTotal:          payloadInt(payload, "task_board_manual_control_success_total"),
			TaskBoardManualControlRejectedTotal:         payloadInt(payload, "task_board_manual_control_rejected_total"),
			TaskBoardManualControlDedupTotal:            payloadInt(payload, "task_board_manual_control_idempotent_dedup_total"),
			TaskBoardManualControlByAction:              payloadIntMap(payload, "task_board_manual_control_by_action"),
			TaskBoardManualControlByReason:              payloadIntMap(payload, "task_board_manual_control_by_reason"),
			SubagentChildTotal:                          payloadInt(payload, "subagent_child_total"),
			SubagentChildFailed:                         payloadInt(payload, "subagent_child_failed"),
			SubagentBudgetRejectTotal:                   payloadInt(payload, "subagent_budget_reject_total"),
			CollabHandoffTotal:                          payloadInt(payload, "collab_handoff_total"),
			CollabDelegationTotal:                       payloadInt(payload, "collab_delegation_total"),
			CollabAggregationTotal:                      payloadInt(payload, "collab_aggregation_total"),
			CollabAggregationStrategy:                   payloadString(payload, "collab_aggregation_strategy"),
			CollabFailFastTotal:                         payloadInt(payload, "collab_fail_fast_total"),
			CollabRetryTotal:                            payloadInt(payload, "collab_retry_total"),
			CollabRetrySuccessTotal:                     payloadInt(payload, "collab_retry_success_total"),
			CollabRetryExhaustedTotal:                   payloadInt(payload, "collab_retry_exhausted_total"),
			RecoveryEnabled:                             payloadBool(payload, "recovery_enabled"),
			RecoveryResumeBoundary:                      payloadString(payload, "recovery_resume_boundary"),
			RecoveryInflightPolicy:                      payloadString(payload, "recovery_inflight_policy"),
			RecoveryRecovered:                           payloadBool(payload, "recovery_recovered"),
			RecoveryReplayTotal:                         payloadInt(payload, "recovery_replay_total"),
			RecoveryTimeoutReentryTotal:                 payloadInt(payload, "recovery_timeout_reentry_total"),
			RecoveryTimeoutReentryExhaustedTotal:        payloadInt(payload, "recovery_timeout_reentry_exhausted_total"),
			RecoveryConflict:                            payloadBool(payload, "recovery_conflict"),
			RecoveryConflictCode:                        payloadString(payload, "recovery_conflict_code"),
			RecoveryFallbackUsed:                        payloadBool(payload, "recovery_fallback_used"),
			RecoveryFallbackReason:                      payloadString(payload, "recovery_fallback_reason"),
			RuntimeReadinessStatus:                      payloadString(payload, "runtime_readiness_status"),
			RuntimeReadinessFindingTotal:                payloadInt(payload, "runtime_readiness_finding_total"),
			RuntimeReadinessBlockingTotal:               payloadInt(payload, "runtime_readiness_blocking_total"),
			RuntimeReadinessDegradedTotal:               payloadInt(payload, "runtime_readiness_degraded_total"),
			RuntimePrimaryDomain:                        payloadString(payload, "runtime_primary_domain"),
			RuntimePrimaryCode:                          payloadString(payload, "runtime_primary_code"),
			RuntimePrimarySource:                        payloadString(payload, "runtime_primary_source"),
			RuntimePrimaryConflictTotal:                 payloadInt(payload, "runtime_primary_conflict_total"),
			RuntimeSecondaryReasonCodes:                 payloadStringSlice(payload, "runtime_secondary_reason_codes"),
			RuntimeSecondaryReasonCount:                 payloadInt(payload, "runtime_secondary_reason_count"),
			RuntimeArbitrationRuleVersion:               payloadString(payload, "runtime_arbitration_rule_version"),
			RuntimeArbitrationRuleRequestedVersion:      payloadString(payload, "runtime_arbitration_rule_requested_version"),
			RuntimeArbitrationRuleEffectiveVersion:      payloadString(payload, "runtime_arbitration_rule_effective_version"),
			RuntimeArbitrationRuleVersionSource:         payloadString(payload, "runtime_arbitration_rule_version_source"),
			RuntimeArbitrationRulePolicyAction:          payloadString(payload, "runtime_arbitration_rule_policy_action"),
			RuntimeArbitrationRuleUnsupportedTotal:      payloadInt(payload, "runtime_arbitration_rule_unsupported_total"),
			RuntimeArbitrationRuleMismatchTotal:         payloadInt(payload, "runtime_arbitration_rule_mismatch_total"),
			RuntimeRemediationHintCode:                  payloadString(payload, "runtime_remediation_hint_code"),
			RuntimeRemediationHintDomain:                payloadString(payload, "runtime_remediation_hint_domain"),
			RuntimeReadinessPrimaryCode:                 payloadString(payload, "runtime_readiness_primary_code"),
			RuntimeReadinessAdmissionTotal:              payloadInt(payload, "runtime_readiness_admission_total"),
			RuntimeReadinessAdmissionBlockedTotal:       payloadInt(payload, "runtime_readiness_admission_blocked_total"),
			RuntimeReadinessAdmissionDegradedAllowTotal: payloadInt(payload, "runtime_readiness_admission_degraded_allow_total"),
			RuntimeReadinessAdmissionBypassTotal:        payloadInt(payload, "runtime_readiness_admission_bypass_total"),
			RuntimeReadinessAdmissionMode:               payloadString(payload, "runtime_readiness_admission_mode"),
			RuntimeReadinessAdmissionPrimaryCode:        payloadString(payload, "runtime_readiness_admission_primary_code"),
			AdapterHealthStatus:                         payloadString(payload, "adapter_health_status"),
			AdapterHealthProbeTotal:                     payloadInt(payload, "adapter_health_probe_total"),
			AdapterHealthDegradedTotal:                  payloadInt(payload, "adapter_health_degraded_total"),
			AdapterHealthUnavailableTotal:               payloadInt(payload, "adapter_health_unavailable_total"),
			AdapterHealthPrimaryCode:                    payloadString(payload, "adapter_health_primary_code"),
			AdapterHealthBackoffAppliedTotal:            payloadInt(payload, "adapter_health_backoff_applied_total"),
			AdapterHealthCircuitOpenTotal:               payloadInt(payload, "adapter_health_circuit_open_total"),
			AdapterHealthCircuitHalfOpenTotal:           payloadInt(payload, "adapter_health_circuit_half_open_total"),
			AdapterHealthCircuitRecoverTotal:            payloadInt(payload, "adapter_health_circuit_recover_total"),
			AdapterHealthCircuitState:                   payloadString(payload, "adapter_health_circuit_state"),
			AdapterHealthGovernancePrimaryCode:          payloadString(payload, "adapter_health_governance_primary_code"),
			EffectiveOperationProfile:                   payloadString(payload, "effective_operation_profile"),
			TimeoutResolutionSource:                     payloadString(payload, "timeout_resolution_source"),
			TimeoutResolutionTrace:                      payloadString(payload, "timeout_resolution_trace"),
			TimeoutParentBudgetClampTotal:               payloadInt(payload, "timeout_parent_budget_clamp_total"),
			TimeoutParentBudgetRejectTotal:              payloadInt(payload, "timeout_parent_budget_reject_total"),
			DiagnosticsCardinalityBudgetHitTotal:        payloadInt(payload, "diagnostics_cardinality_budget_hit_total"),
			DiagnosticsCardinalityTruncatedTotal:        payloadInt(payload, "diagnostics_cardinality_truncated_total"),
			DiagnosticsCardinalityFailFastRejectTotal:   payloadInt(payload, "diagnostics_cardinality_fail_fast_reject_total"),
			DiagnosticsCardinalityOverflowPolicy:        payloadString(payload, "diagnostics_cardinality_overflow_policy"),
			DiagnosticsCardinalityTruncatedFieldSummary: payloadString(payload, "diagnostics_cardinality_truncated_field_summary"),
			GateChecks:                                  payloadInt(payload, "gate_checks"),
			GateDeniedCount:                             payloadInt(payload, "gate_denied_count"),
			GateTimeoutCount:                            payloadInt(payload, "gate_timeout_count"),
			GateRuleHitCount:                            payloadInt(payload, "gate_rule_hit_count"),
			GateRuleLastID:                              payloadString(payload, "gate_rule_last_id"),
			AwaitCount:                                  payloadInt(payload, "await_count"),
			ResumeCount:                                 payloadInt(payload, "resume_count"),
			CancelByUserCount:                           payloadInt(payload, "cancel_by_user_count"),
			CancelPropagated:                            payloadInt(payload, "cancel_propagated_count"),
			BackpressureDrop:                            payloadInt(payload, "backpressure_drop_count"),
			BackpressureDropByPhase:                     payloadIntMap(payload, "backpressure_drop_count_by_phase"),
			InflightPeak:                                payloadInt(payload, "inflight_peak"),
		})
	case "skill.discovered":
		r.manager.RecordSkill(runtimediag.SkillRecord{
			Time:      eventTime(ev.Time),
			RunID:     ev.RunID,
			Action:    "discover",
			Status:    "success",
			LatencyMs: payloadInt64(payload, "latency_ms"),
			Payload:   payload,
		})
	case "skill.warning":
		action := payloadString(payload, "action")
		if action == "" {
			action = "compile"
		}
		errorClass := payloadString(payload, "error_class")
		if errorClass == "" {
			errorClass = string(types.ErrSkill)
		}
		r.manager.RecordSkill(runtimediag.SkillRecord{
			Time:       eventTime(ev.Time),
			RunID:      ev.RunID,
			SkillName:  payloadString(payload, "name"),
			Action:     action,
			Status:     payloadOrDefault(payload, "status", "warning"),
			LatencyMs:  payloadInt64(payload, "latency_ms"),
			ErrorClass: errorClass,
			Payload:    payload,
		})
	case "skill.loaded":
		action := payloadString(payload, "action")
		if action == "" {
			action = "compile"
		}
		r.manager.RecordSkill(runtimediag.SkillRecord{
			Time:      eventTime(ev.Time),
			RunID:     ev.RunID,
			SkillName: payloadString(payload, "name"),
			Action:    action,
			Status:    payloadOrDefault(payload, "status", "success"),
			LatencyMs: payloadInt64(payload, "latency_ms"),
			Payload:   payload,
		})
	}
	if r.exporterRuntime != nil {
		exportCfg := r.manager.EffectiveConfig().Runtime.Observability.Export
		r.exporterRuntime.HandleEvent(exportCfg, types.Event{
			Version:   strings.TrimSpace(ev.Version),
			Type:      strings.TrimSpace(ev.Type),
			RunID:     strings.TrimSpace(ev.RunID),
			Iteration: ev.Iteration,
			Time:      eventTime(ev.Time),
			Payload:   payload,
		})
	}
}

func payloadString(m map[string]any, key string) string {
	if len(m) == 0 {
		return ""
	}
	raw, ok := m[key]
	if !ok {
		return ""
	}
	s, _ := raw.(string)
	return strings.TrimSpace(s)
}

func payloadInt64(m map[string]any, key string) int64 {
	if len(m) == 0 {
		return 0
	}
	raw, ok := m[key]
	if !ok {
		return 0
	}
	switch tv := raw.(type) {
	case int64:
		return tv
	case int:
		return int64(tv)
	case float64:
		return int64(tv)
	default:
		return 0
	}
}

func payloadInt(m map[string]any, key string) int {
	return int(payloadInt64(m, key))
}

func payloadFloat64(m map[string]any, key string) float64 {
	if len(m) == 0 {
		return 0
	}
	raw, ok := m[key]
	if !ok {
		return 0
	}
	switch tv := raw.(type) {
	case float64:
		return tv
	case float32:
		return float64(tv)
	case int:
		return float64(tv)
	case int64:
		return float64(tv)
	default:
		return 0
	}
}

func payloadInt64Map(m map[string]any, key string) map[string]int64 {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	out := map[string]int64{}
	switch src := raw.(type) {
	case map[string]any:
		for k, v := range src {
			switch tv := v.(type) {
			case int64:
				out[k] = tv
			case int:
				out[k] = int64(tv)
			case float64:
				out[k] = int64(tv)
			}
		}
	case map[string]int64:
		for k, v := range src {
			out[k] = v
		}
	case map[string]int:
		for k, v := range src {
			out[k] = int64(v)
		}
	default:
		return nil
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func payloadIntMap(m map[string]any, key string) map[string]int {
	in := payloadInt64Map(m, key)
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]int, len(in))
	for k, v := range in {
		out[k] = int(v)
	}
	return out
}

func payloadStringSlice(m map[string]any, key string) []string {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	out := []string{}
	switch src := raw.(type) {
	case []string:
		for i := range src {
			item := strings.TrimSpace(src[i])
			if item == "" {
				continue
			}
			out = append(out, item)
		}
	case []any:
		for i := range src {
			item, ok := src[i].(string)
			if !ok {
				continue
			}
			item = strings.TrimSpace(item)
			if item == "" {
				continue
			}
			out = append(out, item)
		}
	default:
		return nil
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func payloadStringSliceCSV(m map[string]any, key string) []string {
	if len(m) == 0 {
		return nil
	}
	raw, ok := m[key]
	if !ok {
		return nil
	}
	switch src := raw.(type) {
	case string:
		parts := strings.Split(src, ",")
		out := make([]string, 0, len(parts))
		for i := range parts {
			item := strings.TrimSpace(parts[i])
			if item == "" {
				continue
			}
			out = append(out, item)
		}
		if len(out) == 0 {
			return nil
		}
		return out
	default:
		return payloadStringSlice(m, key)
	}
}

func payloadOrDefault(m map[string]any, key, fallback string) string {
	v := payloadString(m, key)
	if v == "" {
		return fallback
	}
	return v
}

func payloadStringOrFallback(m map[string]any, key, fallback string) string {
	v := payloadString(m, key)
	if v == "" {
		return strings.TrimSpace(fallback)
	}
	return v
}

func payloadIntOrFallback(m map[string]any, key string, fallback int) int {
	if len(m) == 0 {
		return fallback
	}
	if _, ok := m[key]; !ok {
		return fallback
	}
	return payloadInt(m, key)
}

func payloadBool(m map[string]any, key string) bool {
	if len(m) == 0 {
		return false
	}
	raw, ok := m[key]
	if !ok {
		return false
	}
	v, _ := raw.(bool)
	return v
}

func eventTime(ts time.Time) time.Time {
	if ts.IsZero() {
		return time.Now()
	}
	return ts
}

func shouldAutoGenerateDiagnosticsBundle(
	manager *runtimeconfig.Manager,
	bundleTotal int,
	bundleStatus string,
	bundleSchemaVersion string,
	bundleReasonCode string,
) bool {
	if manager == nil {
		return false
	}
	cfg := manager.EffectiveConfig().Runtime.Diagnostics.Bundle
	if !cfg.Enabled {
		return false
	}
	if bundleTotal > 0 {
		return false
	}
	if strings.TrimSpace(bundleStatus) != "" {
		return false
	}
	if strings.TrimSpace(bundleSchemaVersion) != "" {
		return false
	}
	if strings.TrimSpace(bundleReasonCode) != "" {
		return false
	}
	return true
}

func normalizeRuntimeObservabilityExportProfile(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeObservabilityExportProfileOTLP:
		return runtimeconfig.RuntimeObservabilityExportProfileOTLP
	case runtimeconfig.RuntimeObservabilityExportProfileLangfuse:
		return runtimeconfig.RuntimeObservabilityExportProfileLangfuse
	case runtimeconfig.RuntimeObservabilityExportProfileCustom:
		return runtimeconfig.RuntimeObservabilityExportProfileCustom
	case runtimeconfig.RuntimeObservabilityExportProfileNone:
		return runtimeconfig.RuntimeObservabilityExportProfileNone
	default:
		return runtimeconfig.RuntimeObservabilityExportProfileNone
	}
}

func normalizeRuntimeObservabilityExportStatus(raw string, profile string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case RuntimeExportStatusDisabled:
		return RuntimeExportStatusDisabled
	case RuntimeExportStatusSuccess:
		return RuntimeExportStatusSuccess
	case RuntimeExportStatusDegraded:
		return RuntimeExportStatusDegraded
	case RuntimeExportStatusFailed:
		return RuntimeExportStatusFailed
	default:
		if normalizeRuntimeObservabilityExportProfile(profile) == runtimeconfig.RuntimeObservabilityExportProfileNone {
			return RuntimeExportStatusDisabled
		}
		return RuntimeExportStatusSuccess
	}
}

func normalizeRuntimeDiagnosticsBundleStatus(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case runtimeconfig.RuntimeDiagnosticsBundleStatusDisabled:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusDisabled
	case runtimeconfig.RuntimeDiagnosticsBundleStatusSuccess:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusSuccess
	case runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded
	case runtimeconfig.RuntimeDiagnosticsBundleStatusFailed:
		return runtimeconfig.RuntimeDiagnosticsBundleStatusFailed
	default:
		return ""
	}
}

func normalizeRuntimeDiagnosticsBundleReasonCode(raw string, status string) string {
	normalizedStatus := normalizeRuntimeDiagnosticsBundleStatus(status)
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		if normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusFailed || normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded {
			return runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown
		}
		return ""
	case runtimeconfig.RuntimeDiagnosticsBundleReasonOutputUnavailable:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonOutputUnavailable
	case runtimeconfig.RuntimeDiagnosticsBundleReasonPolicyInvalid:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonPolicyInvalid
	case runtimeconfig.RuntimeDiagnosticsBundleReasonMaxSizeExceeded:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonMaxSizeExceeded
	case runtimeconfig.RuntimeDiagnosticsBundleReasonSectionMissing:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonSectionMissing
	case runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown:
		return runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown
	default:
		if normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusFailed || normalizedStatus == runtimeconfig.RuntimeDiagnosticsBundleStatusDegraded {
			return runtimeconfig.RuntimeDiagnosticsBundleReasonUnknown
		}
		return ""
	}
}

func normalizeRuntimeDiagnosticsBundleSchemaVersion(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		return ""
	case runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1:
		return runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1
	default:
		return runtimeconfig.RuntimeDiagnosticsBundleSchemaVersionV1
	}
}

var _ types.EventHandler = (*RuntimeRecorder)(nil)
